### ISSUE TITLE
Why I am getting this output?

### ISSUE THREAD

**Issue by bubnenkoff** [ikod/dlang-requests#1]
I just want to get response code, but getting on console a lot of unneeded info:
http://img.ctrlv.in/img/16/04/24/571d018304c8d.png

**Comment by ikod** [comment]
Hello,

seems like you have global log at level 'trace'. Try to call
```
import std.experimental.logger;
globalLogLevel(LogLevel.info);

```
before calling Request.get()

**Comment by bubnenkoff** [comment]
Yeah, it's work! How to fix this issue? I read docs about logger, but did not understand how to change it's level

**Comment by ikod** [comment]
btw, code 301 should redirect to 'Location' (it is bug if you receive response with code 301 and it will be fixed soon). 
You can use `exec!'HEAD'(url);` to test server availability.

**Comment by bubnenkoff** [comment]
http://img.ctrlv.in/img/16/04/24/571d0d7ad5207.png

**Comment by ikod** [comment]
sorry, mistype. should be exec!"HEAD" - string must be doublequotes

**Comment by bubnenkoff** [comment]
Thanks!
I still can't understand why if do not do:
import std.experimental.logger;
globalLogLevel(LogLevel.info);

 I am getting such output http://img.ctrlv.in/img/16/04/24/571d0f134ee4c.png

**Comment by bubnenkoff** [comment]
Maybe you have any good idea how to check Arangodb server status. The idea to check if it's for 301 codes and so, looks bad

**Comment by ikod** [comment]
re loglevel I have no answer :)
as for monitoring Arangodb maybe this will help https://docs.arangodb.com/HttpAdministrationAndMonitoring/index.html
