### ISSUE TITLE
Response headers aren't documented

### ISSUE THREAD

**Issue by wilzbach** [ikod/dlang-requests#11]
I tried to find `responseHeaders` on your documentation: http://htmlpreview.github.io/?https://github.com/ikod/dlang-requests/blob/master/docs/http.html

but couldn't find them. A quick look at the code shows that you do have them - is the documentation out of date or is this a problem with the documentation generator?

**Comment by wilzbach** [comment]
a workaround for mixins not documented could be

```
version (StdDdoc)
    {
``

**Comment by ikod** [comment]
Hello,

I was unable to to find nice way to document mixins, so I just added doc lines.

**Comment by wilzbach** [comment]
Okay great - btw if you want to setup more visually appealing docs, I tried a lot of approaches for mir, but finally sticked with ddoc and the dlang.org stylesheet. It has the additional benefit (apart from looking great) that you can test your module directly with the official docs.

Feel free to copy or ping me if you need help.

https://github.com/libmir/mir/tree/master/doc
http://docs.mir.dlang.io/

**Comment by ikod** [comment]
@wilzbach 
Hello!
I implemented almost all functionality I planned for start, so I'll mostly busy with bug fixes and simple features implementation. And there are still unsolved problems I can recall:

1.  Docs cleanup and Phobos style docs. I need some help with styles.
2. Testing without internet access. I still choose from several options (use vibe.d? write small http-server?)
3. external uri parser?
Anything I missed?

**Comment by wilzbach** [comment]
> I implemented almost all functionality I planned for start, so I'll mostly busy with bug fixes and simple features implementation.

Sweet!

> Docs cleanup and Phobos style docs. I need some help with styles.

http://dlang.org/dstyle.html
https://wiki.dlang.org/Contributing_to_Phobos

- `Params` and `Returns` are needed for all public functions
- multiple `///` look rather weird, better use `/** .... */`
- `$(B .)` for the parameter list

I am also quite young to Dlang, so you should better ping at least the people in #10 (they are more experienced).

> Testing without internet access. I still choose from several options (use vibe.d? write small http-server?)

`Vibe.d` is unfortunately not possible for Phobos (in the near future) :/

> external uri parser?

didn't @JackStouffer do some experiments on this?

**Comment by ikod** [comment]
I'm closing old issues.
Response now documented in https://ikod.github.io/dlang-requests/requests/base/Response.html
Thanks
