### ISSUE TITLE
http://code.dlang.org/packages/requests state no-dependencies => cachetools required

### ISSUE THREAD

**Issue by Robert-M-Muench** [ikod/dlang-requests#113]
The dependency should be added.

**Comment by ikod** [comment]
Hello @Robert-M-Muench 

Sorry, but I can't find place on code.dlang.org where I can add this dependency. There is only dub.json, and dependency already there.

Thanks for any further info.

**Comment by Robert-M-Muench** [comment]
![image](https://user-images.githubusercontent.com/1826391/69501055-6b6e5c00-0f01-11ea-95f8-fc25af95f627.png)

On the left side over versions. There I would expect all dependencies to other packages. Other 's are listing them.

**Comment by ikod** [comment]
Hello @Robert-M-Muench 
I see. I suspect that code.dlang.org incorrectly parse dub.json in this case.. I'll try to refactor dub.json and see if this helps.

**Comment by ikod** [comment]
Hello @Robert-M-Muench 

Yes, dub.json refactoring helped.
Thanks for report.
