### ISSUE TITLE
request with proxys dont work

### ISSUE THREAD

**Issue by hackerboy1337** [ikod/dlang-requests#117]
Doing a request with proxy does not work.

object.Exception@/home/.dub/packages/requests-1.0.14/requests/source/requests/streams.d(798): ssl connect failed:

**Comment by ikod** [comment]
Hello @hackerboy1337 

Can you please show how dld you configure proxy url?

Thanks

**Comment by hackerboy1337** [comment]
`import std.stdio;

import requests;

void main(string[] args) {
    Request req = Request();
    req.proxy = "http://hampros2:KtE6kyChRIf7Gn@149.202.218.99:31006";
    Response res = req.get("https://google.com");
    writeln(res.responseBody);
}`

**Comment by ikod** [comment]
@hackerboy1337 

confirmed. Will post fix ASAP

**Comment by ikod** [comment]
@hackerboy1337 
Can you please check with latest commit?

**Comment by hackerboy1337** [comment]
object.Exception@../../.dub/packages/requests-1.0.14/requests/source/requests/streams.d(798): ssl connect failed: unexpected eof while reading

**Comment by ikod** [comment]
Can you, please run this app. and show me complete output?
```
import std.stdio;

import requests;
import std.experimental.logger;

void main(string[] args) {
    globalLogLevel = LogLevel.trace;
    Request req = Request();
    req.verbosity = 2;
    req.proxy = "http://hampros2:KtE6kyChRIf7Gn@149.202.218.99:31006";
    Response res = req.get("https://google.com");
}
```
as it works for me

**Comment by hackerboy1337** [comment]
```
> CONNECT google.com:443 HTTP/1.1
< HTTP/1.1 407 Unauthorized
content-length: 112
cache-control: no-cache
content-type: text/html
proxy-authenticate: Basic realm="proxy"
connection: close

<html><body><h1>407 Unauthorized</h1>
You need a valid user and password to access this content.
</body></html>

object.Exception@../../.dub/packages/requests-1.0.14/requests/source/requests/streams.d(798): ssl connect failed: unexpected eof while reading
----------------
streams.d:798 [0x55fa898952b7]
streams.d:861 [0x55fa898957cd]
http.d:680 [0x55fa897f946b]
http.d:2168 [0x55fa897fcd6b]
http.d:2392 [0x55fa89800094]
request.d:499 [0x55fa898319a0]
request.d:184 [0x55fa8983141d]
request.d:632 [0x55fa8983208b]
request.d:528 [0x55fa898320f9]
app.d:11 [0x55fa897e44a0]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7fe44b299e8f]
??:? _d_run_main2 [0x7fe44b299c9e]
??:? _d_run_main [0x7fe44b299afd]
entrypoint.d:35 [0x55fa897e47a4]
??:? __libc_start_main [0x7fe44aea4022]
??:? [0x55fa897e416d]
```

**Comment by hackerboy1337** [comment]
maybe dub is not fetching the latest version? on https://code.dlang.org/packages/requests it says "1.0.14 released a month ago"

how do i make it fetch the latest github?

**Comment by ikod** [comment]
> maybe dub is not fetching the latest version? on https://code.dlang.org/packages/requests it says "1.0.14 released a month ago"
> 
> how do i make it use the latest github?

for example:
```
cd /tmp/
git clone https://github.com/ikod/dlang-requests.git
```
Then in the your test project:
1. in dub.json **replace dependency** for requests with:
```
	"dependencies": {
		"requests": {
			"path": "/tmp/dlang-requests"
		}
	},
```
2. **remove dub.selection.json**
3. dub run

**Comment by hackerboy1337** [comment]
Thanks. It works!

**Comment by ikod** [comment]
Thanks for report!
