### ISSUE TITLE
404 on API docs of request.base and request.request

### ISSUE THREAD

**Issue by zorael** [ikod/dlang-requests#119]
https://ikod.github.io/dlang-requests/requests/base.html
https://ikod.github.io/dlang-requests/requests/request.html

> 404
> File not found
> 
> The site configured at this address does not contain the requested file.
> 
> If this is your site, make sure that the filename case matches the URL.
> For root URLs (like http://example.com/) you must provide an index.html file.

**Comment by ikod** [comment]
Hello @zorael 

Thanks! Should work now.
