### ISSUE TITLE
read/modify postData in Intercepter

### ISSUE THREAD

**Issue by skoppe** [ikod/dlang-requests#120]
With interceptors we can modify some aspects of the request and the response.

Modifying postData is rather difficult however, because it has input range semantics. Which means iterating it in a interceptor leaves it empty.

I tried iterating it and creating a fresh postData for the next request, but I can't construct an `InputRangeAdapter` since it is private.

What about modifying `makeAdapter` to be public?

**Comment by ikod** [comment]
Hello, @skoppe 

Ok, I thinks this is possible. I will look if there any other solutions in few hours.

Thanks for report

**Comment by ikod** [comment]
Hello, @skoppe 

Looks like making makeAdapter public works ok for me. I was able to run such code and received expected output:

```
import std.stdio;
import std.string;
import std.algorithm;
import requests;

class I : Interceptor
{
    Response opCall(Request rq, RequestHandler next)
    {
	rq.postData = makeAdapter(rq.postData.map!"toUpper(cast(string)a)");
        auto rs = next.handle(rq);
	return rs;
    }
}

void main()
{
    auto f = File("text.txt", "rb");
    Request rq;
    rq.verbosity = 1;
    rq.addInterceptor(new I);
    auto rs = rq.post("https://httpbin.org/post", f.byChunk(5));
    writeln(rs.responseBody);
}
```
Is it ok for you& Or you have different usecase?

**Comment by skoppe** [comment]
That is perfect! Exactly what I needed. Thanks for the quick response :)

**Comment by ikod** [comment]
Should be in v1.1.2 now.
Thanks!
