### ISSUE TITLE
bug: failed to addHeader ("Content-Length": "0"), when called from rq.post(url, [])

### ISSUE THREAD

**Issue by mingwugmail** [ikod/dlang-requests#122]
suppose the post does not take any params, and we pass empty array to:
```
  auto rs = rq.post(url, [])
```
This call will fail, with error:
```
{"fault":{"faultstring":"Content-Length is missing","detail":{"errorcode":"messaging.adaptors.http.flow.LengthRequired"}}}
```

I find the answer here:
https://help.salesforce.com/articleView?id=000337925&language=en_US&mode=1&type=1

```
The content length header is missing.

If size of the entity body is known add it in the header. If the body is not present you can specify the length as 0.
req.setHeader('Content-Length', '0');

NOTE: POST requests require the Content-Length header to be set.
```

I set the `rq.verbosity = 2;`, and checked, in the above scenario, 'Content-Length' is missing, manually set it to 0 fix the problem. But I think this is bug need to be fixed, i.e. the library should  *always* set "Content-Length": "0" (even if it's 0).

**Comment by ikod** [comment]
Thanks for report, will check in few hours.

пт, 15 мая 2020 г., 20:21 mingwugmail <notifications@github.com>:

**Comment by ikod** [comment]
Hello, @mingwugmail 

This should be fixed in current release, check please

**Comment by mingwugmail** [comment]
@ikod yes, it's working! Thank you! requests rocks!
