### ISSUE TITLE
nitpicking: requests.lib(package.obj) : warning LNK4255: library contain multiple objects of the same name; linking object as if no debug info

### ISSUE THREAD

**Issue by mingwugmail** [ikod/dlang-requests#124]
on Windows 10, there is a warning message at linking stage:

```
Linking...
requests.lib(package.obj) : warning LNK4255: library contain multiple objects of the same name; linking object as if no debug info
```

Not sure what it's complaining, and how to fix it? add some flags some where?

**Comment by ikod** [comment]
Hello @mingwugmail 

> on Windows 10, there is a warning message at linking stage:
> 
> ```
> Linking...
> requests.lib(package.obj) : warning LNK4255: library contain multiple objects of the same name; linking object as if no debug info
> ```
> 
> Not sure what it's complaining, and how to fix it? add some flags some where?

As long as this is warning, I think you can safely ignore it. Anyway I do not know how to fix it as i have no Windows to test right now.
