### ISSUE TITLE
[enhancement] allow user pass in logger object (which defaults to stdout)

### ISSUE THREAD

**Issue by mingwugmail** [ikod/dlang-requests#125]
Right now, when verbosity > 0, requests use writeln to print out message; for a long running background job, I want the message to be logged. While:

./myapp > requests.log

can be a work-around. But my app internally use a logger.txt already (just std.experimental.logger), I want everything be logged together.

So I'm wondering if we can pass in an logger object (which defaults to std.experimental.logger.filelogger  stdout) when user call:
```
  auto rq = getRequest(mylogger);
```
or even:
```
  req.logger = mylogger;
```

and internally, change `writeln` to :
```
    logger.trace("trace");
    logger.info("info");
    logger.warning("warning");
    logger.error("error");
    logger.critical("critical");
    logger.fatal("fatal");
```

**Comment by ikod** [comment]
Hello @mingwugmail 

You already can add any fancy logging to each request. Just use Interceptors (https://github.com/ikod/dlang-requests#interceptors).
It's easy:

```
import std.stdio;
import std.experimental.logger;

import requests;
import coloredlogger;

ColoredLogger logger; // define your logger

// define your logging action for every request
class LoggerInterceptor : Interceptor {
    Response opCall(Request r, RequestHandler next)
    {
        // here you have access to each request and response details
        logger.infof("Request  %s", r);
        auto rs = next.handle(r);
        logger.infof("Response %s", rs.responseHeaders);
        return rs;
    }
}

static this()
{
    // initialize logger at application start
    logger = new ColoredLogger(stdout, LogLevel.all);
    // add module-level interceptor to Requests
    requests.addInterceptor(new LoggerInterceptor());
}

void main()
{
    // use requests as before
    getContent("http://httpbin.org/get");
}
```

You even don't need to change your app logic or code.

It it ok for you?

**Comment by mingwugmail** [comment]
Thank you, it works great. I missed that in the doc.
