### ISSUE TITLE
Crash on windows in GitHub CI

### ISSUE THREAD

**Issue by WebFreak001** [ikod/dlang-requests#127]
Since I upgraded the requests library from `~>1.0.11` to `1.1.6` the GitHub CI task on Windows seems to consistently fail at runtime with some cryptic error code like `-1073741819`. See https://github.com/Pure-D/serve-d/runs/918303944

I believe it might load some library differently now (like different OpenSSL version), however I can't really see why it would do that based on the diff as the original `libssl32.dll` is still the first entry. Do you have any idea what could cause this? I cannot reproduce the issue on an actual Windows machine.

I don't actually call any requests functions, so I believe this is some issue in a module constructor like the OpenSSL loader.

If there is any configuration flag to completely omit the ssl_adapter module I would use that, as I have implemented a manual download using the WinHTTP APIs instead of using requests just for the windows platform.

Diff: https://github.com/ikod/dlang-requests/compare/v1.0.15...v1.1.6

**Comment by ikod** [comment]
Hello, @WebFreak001 

I do not see any serious windows-related changes. You can try to add 

"debugVersions": ["requests"], to dub.json  and enable LogLevel.trace to see what happens. If this will not help I'll fork your project and will try to debug.

> If there is any configuration flag to completely omit the ssl_adapter module I would use that, as I have implemented a manual download using the WinHTTP APIs instead of using requests just for the windows platform.

No, but I can implement it

**Comment by WebFreak001** [comment]
> I do not see any serious windows-related changes.

I believe fcd2f8caf48e84f939f2d4ead8dcd6b13fe68b94 might have broken it:

before it simply failed loading the libssl dll, now it actually loads some dll but it's missing some functions and thus crashes trying to call them

**Comment by WebFreak001** [comment]
Indeed it is dlang-requests causing this crash as illustrated in this minimal test case: https://github.com/WebFreak001/test-github-ci-requests/runs/932964725

**Comment by WebFreak001** [comment]
>> If there is any configuration flag to completely omit the ssl_adapter module I would use that, as I have implemented a manual download using the WinHTTP APIs instead of using requests just for the windows platform.
>
> No, but I can implement it

nvm that! It seems I can just not trigger it by not importing requests, so I will put the import in a version block.

**Comment by WebFreak001** [comment]
> nvm that! It seems I can just not trigger it by not importing requests, so I will put the import in a version block.

actually it seems like it would be useful after all, I seem to be having some more complex issue with my package tree where the version block doesn't fix it.

Additionally if you add a dub sub configuration for this (something called like "noSharedCtor") you could put the initialization call into some function which one can manually call if that sub configuration is enabled. Depending on an applications requirements this might be important.

**Comment by ikod** [comment]
Hello @WebFreak001 

I can see two solutions here
1. have configuration parameter to disable ssl
2. try to configure ssl at the first ssl usage

Will try to investigate during weekend

**Comment by ikod** [comment]
Hello @WebFreak001 

Sorry for long delay. You can check changes here: https://github.com/ikod/dlang-requests/commit/2e164f4ffdf35a28edfad790c56a5c44b2388b92
version to disable SSL is "RequestsSkipSSL"
If it is ok for you I'll make new release.
