### ISSUE TITLE
Issue with cloudflare certificate and https links 

### ISSUE THREAD

**Issue by RUSshy** [ikod/dlang-requests#132]
Hello

I have a website, i use the automatic cloudflare HTTPS redirect, it uses their own certificate automatically

I get the following whenever i do a get request

```
ssl connect failed: certificate verify failed
```

Unfortunately i can't provide links, maybe this will be enought (from google chrome):

![image](https://user-images.githubusercontent.com/18348637/117224369-07e3a000-ae10-11eb-98e0-2bec2c4a53fb.png)

![image](https://user-images.githubusercontent.com/18348637/117224387-15008f00-ae10-11eb-92cd-c841e1d0b804.png)

**Comment by RUSshy** [comment]
Using ``rq.sslSetVerifyPeer(false);`` fixed the issue

**Comment by RUSshy** [comment]
I have users who report this issue:

``can't complete call to TLS_method``

Can't share website publicly, how can i contact you?

**Comment by ikod** [comment]
> I have users who report this issue:
> 
> `can't complete call to TLS_method`
> 
> Can't share website publicly, how can i contact you?

igor.khasilev @ gmail.com
