### ISSUE TITLE
can't complete call to TLS_method

### ISSUE THREAD

**Issue by Aphexus** [ikod/dlang-requests#139]
Delete.

**Comment by ikod** [comment]
Hello @Aphexus 

Most likely something changed in path to dlls. Please check that your neew code can find and load openssl dll's.

Links that may help:

- https://github.com/ikod/dlang-requests#windows-ssl-notes
- https://github.com/ikod/dlang-requests/issues/77#issuecomment-405911012

You can create simplest project mentioned in second link to test if requests can find SSL libs.

Feel free to ask any further questions if you have.

**Comment by ikod** [comment]
Hello @Aphexus ,

> So this had nothing to do with `requests` and ultimately stemmed from the Visual D and Visual Studio 2022 update breaking x86 debugging leading me to use the older x64 setup which ended up overriding my ability to use the x86 build. (sounds complex, maybe it is but it's pretty basic issue of like having two exe's in two paths on the path env var and one getting called first(the wrong one of course))

Yes, looks like this can be a problem. I'm not a windows programmer, I have only very basic knowledge on the process of DLL lookup in Windows, so I can't give any hint for solution.
> 
> Don't you love programming? ;)

I do :)

**Comment by ikod** [comment]
Hello @Aphexus 

Can I help more with this?
