### ISSUE TITLE
Program exited with code -13 when uploading artifact to GitHub API

### ISSUE THREAD

**Issue by andrewlalis** [ikod/dlang-requests#144]
I'm using requests to create releases via the GitHub REST API, and this includes first creating a release, and then uploading artifacts as binary data to the release. See below:
https://docs.github.com/en/rest/releases/releases#create-a-release
https://docs.github.com/en/rest/releases/assets#upload-a-release-asset

The problem is that the request fails by saying "Program exited with code -13", without any mention of what the underlying error is.
```d
string responseBody = cast(string) response.responseBody;
JSONValue responseData = parseJSON(responseBody);
print("Created release %s", responseData["url"].str);
long releaseId = responseData["id"].integer;
string uploadUrl = format!"https://uploads.github.com/repos/andrewlalis/RailSignalAPI/releases/%d/assets?name=%s"(
    releaseId,
    "rail-signal-" ~ ver ~ ".jar"
);
print("Uploading JAR file to %s", uploadUrl);
auto f = File("./target/rail-signal-" ~ ver ~ ".jar", "rb");
auto assetResponse = rq.post(uploadUrl, f.byChunk(4096)); // This causes the error.
```
The verbose output of the final post call is:
```
> POST /repos/andrewlalis/RailSignalAPI/releases/68534282/assets?name=rail-signal-2.2.1.jar HTTP/1.1
> User-Agent: dlang-requests
> Accept-Encoding: gzip,deflate
> Authorization: Basic REDACTED
> Host: uploads.github.com
> Connection: Keep-Alive
> Transfer-Encoding: chunked
> Content-Type: application/octet-stream
> 
Program exited with code -13
```

**Comment by ikod** [comment]
Hello, @andrewlalis 

Can you please set request verbosity level to 3, and also include flag
`-debug=requests`
to your dub.json?

**Comment by andrewlalis** [comment]
I did as you suggest, and indeed additional debug information is given, however during the file upload, the majority of this output is the garbled raw binary output of the file which is being uploaded, and occasionally I see the following messages:
```
2022-06-03T14:13:41.164 [trace] http.d:1724:sendChunkedContent chunk sent
2022-06-03T14:13:41.164 [trace] http.d:1720:sendChunkedContent sending 1000
```
But the program once again terminates without completing the upload. If you like, I could prepare a more extensive sample to replicate this issue, this evening.

**Comment by ikod** [comment]
Thanks,

If you can prepare test, so that I can reproduce and debug problem - it
would be nice! Or you can send me debug output, maybe I'll see what
happened.

пт, 3 июн. 2022 г., 15:16 Andrew Lalis ***@***.***>:

**Comment by andrewlalis** [comment]
@ikod 
I have prepared a sample project which illustrates this bug: https://github.com/andrewlalis/DRequestsAssetUploadTest
Instructions for how to run the code are in the README. You can either fork the repository and update the URLs to point to your copy, or I can add you as a collaborator to that repository, if you prefer.

The project tries to create a release and upload an asset, but fails during the upload of the asset file, without returning a `Response`, and as you will see if you run it, the release which is created does not have any assets aside from the default things which GitHub adds.

**Comment by ikod** [comment]
@andrewlalis 

Thanks!
will try and report progress

**Comment by ikod** [comment]
@andrewlalis 

confirmed SIGPIPE signal, looking into reasons.

**Comment by ikod** [comment]
@andrewlalis 

Ok, here is fix:

```diff
        Request rq = prepareRequest();
        File f = File(assetFile, "rb");
+       auto size = f.size();
+       rq.addHeaders(["Content-Length": format("%d", size)]);
        Response rp = rq.post(uploadUrl, f.byChunk(4096));

```

and description...
Gitgub asset API requires Content-Length in POST request ([see here](https://docs.github.com/en/rest/releases/assets#upload-a-release-asset)):

> Most libraries will set the required Content-Length header automatically. Use the required Content-Type header to provide the media type of the asset.

but if you use range of chunks as POST body, then library can't determine length of content and can't place `Content-Length` header into headers of POST request. As consequence - github server closes connection as soon as it see that you send post body without Content-Length.

Right now I don't know how to handle such sort of problem properly.

**Comment by andrewlalis** [comment]
Yes! This fixes it. Thank you very much for your help.
