### ISSUE TITLE
OpenSSL 3.0 may be not supported.

### ISSUE THREAD

**Issue by ledyba** [ikod/dlang-requests#148]
Hi, I'm using VSCode plugin on Ubuntu 22.04 (x86_64):

[D Programming Language (code-d) - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=webfreak.code-d)

However, output says:

```
[Info  - 8:23:03 PM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests-1.1.7/requests/source/requests/ssl_adapter.d(193): loading openssl: unknown version for init
```

It looks this error happens here:

https://github.com/ikod/dlang-requests/blob/57846267bb0f88c33338e387664dd9ce2827e424/source/requests/ssl_adapter.d#L190-L199

Is there no OpenSSL 3.0 support? (Ubuntu 22.04 ships with openssl 3.0)

**Comment by ikod** [comment]
Hello @ledyba 

> [Info  - 8:23:03 PM] Connection to server got closed. Server will restart.
> object.Exception@../../../.dub/packages/requests-1.1.7/requests/source/requests/ssl_adapter.d(193): loading openssl: unknown version for init
> ```
> 
> It looks this error happens here:
> Is there no OpenSSL 3.0 support? (Ubuntu 22.04 ships with openssl 3.0)

1.1.7 is quite old, it is possible that it do not support openssl 3. Current version is 2.0.9

Hope this helps

**Comment by ledyba** [comment]
@ikod Thanks, I will report this to [serve-d](https://github.com/Pure-D/serve-d) team.
