### ISSUE TITLE
How to make a request without content-type header?

### ISSUE THREAD

**Issue by bagomot** [ikod/dlang-requests#151]
I need to make a post-request without a body and without a content-type header. As I understand it, the library adds a default content-type. Is there a way to make such a request without a header?

**Comment by ikod** [comment]
Hello, @bagomot 

request.removeHeaders(["Content-Type"]) shoud work for this.
As for body - just do not use it.

If this will not work for you -  please make small code sample I can test and fix it.

Thanks!
