### ISSUE TITLE
Request struct reusing causing exceptions and SegFault

### ISSUE THREAD

**Issue by oracle1wr** [ikod/dlang-requests#154]
Hi,
I tried to create one Request struct value to make sure I have only one for multiple calls. But looks like it gives me exceptions time to time and segFaults.

```
        rq.useStreaming = true;
        rq.verbosity = 0;
        rq.addHeaders(["Icy-MetaData": "1"]);
        rq.timeout(30.seconds);
        auto rs = rq.get(streamUrl);        
```

It is guaranteed, only one thread at a time can use Request. Can you please help with this?

Error example:
```
ERROR: core.exception.ArraySliceError@std/uni/package.d(9035): slice [0 .. 27] extends past source array of length 16
----------------
??:? onArraySliceError [0x563ea71a996e]
??:? _d_arraybounds_slicep [0x563ea7174386]
??:? pure @safe immutable(char)[] std.uni.toCase!(std.uni.toLowerIndex(dchar), 1433, std.uni.toLowerTab(ulong), std.ascii.toLower, immutable(char)[]).toCase(immutable(char)[]) [0x563ea71a109f]
??:? pure @trusted immutable(char)[] std.uni.toLower!(immutable(char)[]).toLower(return scope immutable(char)[]) [0x563ea71a0fff]
??:? pure @safe immutable(char)[] std.uni.toLower(return scope immutable(char)[]) [0x563ea719e48b]
/home/psyscout/.dub/packages/requests-2.0.9/requests/source/requests/http.d:504 void requests.http.HTTPRequest.parseResponseHeaders(in ubyte[], immutable(char)[]) [0x563ea712ee30]
/home/psyscout/.dub/packages/requests-2.0.9/requests/source/requests/http.d:796 void requests.http.HTTPRequest.receiveResponse(requests.streams.NetworkStream) [0x563ea7130acb]
/home/psyscout/.dub/packages/requests-2.0.9/requests/source/requests/http.d:2255 requests.http.HTTPResponse requests.http.HTTPRequest.exec_from_parameters() [0x563ea7134d11]
/home/psyscout/.dub/packages/requests-2.0.9/requests/source/requests/http.d:2415 requests.http.HTTPResponse requests.http.HTTPRequest.execute(requests.request.Request) [0x563ea7135922]
/home/psyscout/.dub/packages/requests-2.0.9/requests/source/requests/request.d:499 requests.base.Response requests.request.Request.LastInterceptor.opCall(requests.request.Request, requests.request.RequestHandler) [0x563ea710ba8e]
/home/psyscout/.dub/packages/requests-2.0.9/requests/source/requests/request.d:184 requests.base.Response requests.request.RequestHandler.handle(requests.request.Request) [0x563ea710abda]
/home/psyscout/.dub/packages/requests-2.0.9/requests/source/requests/request.d:631 requests.base.Response requests.request.Request.execute(immutable(char)[], immutable(char)[], std.typecons.Tuple!(immutable(char)[], "key", immutable(char)[], "value").Tuple[]) [0x563ea710c7fe]
/home/psyscout/.dub/packages/requests-2.0.9/requests/source/requests/request.d:528 requests.base.Response requests.request.Request.get(immutable(char)[], std.typecons.Tuple!(immutable(char)[], "key", immutable(char)[], "value").Tuple[]) [0x563ea710bd68]
source/stream/scanner.d:38 immutable(char)[] stream.scanner.Scanner.getStreamMetadataPos(immutable(char)[]) [0x563ea7065842]
source/stream/orchestrator.d:42 immutable(char)[] stream.orchestrator.Orchestrator.scanTask(immutable(char)[], shared(stream.storage.Storage), stream.scanner.Scanner) [0x563ea7064397]
/home/psyscout/.dvm/compilers/dmd-2.102.2/linux/bin/../../src/phobos/std/parallelism.d:444 void std.parallelism.Task!(stream.orchestrator.Orchestrator.scanTask(immutable(char)[], shared(stream.storage.Storage), stream.scanner.Scanner), immutable(char)[], shared(stream.storage.Storage), stream.scanner.Scanner).Task.impl(void*) [0x563ea7064ce3]
??:? void std.parallelism.AbstractTask.job() [0x563ea7186f76]
??:? void std.parallelism.TaskPool.doJob(std.parallelism.AbstractTask*) [0x563ea71870b3]
??:? void std.parallelism.TaskPool.executeWorkLoop() [0x563ea7187222]
??:? void std.parallelism.TaskPool.startWorkLoop() [0x563ea71871cb]
??:? void core.thread.context.Callable.opCall() [0x563ea717a62c]
??:? thread_entryPoint [0x563ea717a10a]
??:? [0x7f201d71f608]
??:? clone [0x7f201d4ca132]
```

**Comment by ikod** [comment]
> Hi, I tried to create one Request struct value to make sure I have only one for multiple calls. But looks like it gives me exceptions time to time and segFaults.
> 
> ```
>         rq.useStreaming = true;
>         rq.verbosity = 0;
>         rq.addHeaders(["Icy-MetaData": "1"]);
>         rq.timeout(30.seconds);
>         auto rs = rq.get(streamUrl);        
> ```
> 
> It is guaranteed, only one thread at a time can use Request. Can you please help with this?
> 
> Error example:
> 
> ```
> ERROR: core.exception.ArraySliceError@std/uni/package.d(9035): slice [0 .. 27] extends past source array of length 16
> ----------------
> ??:? onArraySliceError [0x563ea71a996e]
> ??:? _d_arraybounds_slicep [0x563ea7174386]
> ??:? pure @safe immutable(char)[] std.uni.toCase!(std.uni.toLowerIndex(dchar), 1433, std.uni.toLowerTab(ulong), std.ascii.toLower, immutable(char)[]).toCase(immutable(char)[]) [0x563ea71a109f]

Hello, @oracle1wr 
Thanks for report. Looks like something with unicode decoding... Can you give me please complete test case, or at least url to test?

Thanks

**Comment by oracle1wr** [comment]
Here is an app.d sample.

```

import std.stdio;
import requests;
import std.stdio;
import std.datetime;
import std.net.curl;
import std.conv: to, toChars;
import std.utf: decode, toUTF8;
import std.array: empty;
import std.algorithm:startsWith;

import core.thread: Thread;

class Scanner {
	Request rq = Request();

    string getStreamMetadataPos(string streamUrl){        
        if(streamUrl.empty){
            throw new Exception("Failed to scan empty Url!");
        } 

        if(streamUrl.startsWith("https:")){
            streamUrl = "http://"~streamUrl[8..$];
        } else if(!streamUrl.startsWith("http:")){
            streamUrl = "http://"~streamUrl;
        }
        string meta;
        //rq.clearHeaders;
		try { 			
			//auto rq = Request();
			rq.useStreaming = true;
			rq.verbosity = 0;
			rq.addHeaders(["Icy-MetaData": "1"]);
			rq.timeout(30.seconds);
			auto rs = rq.get(streamUrl);        
			if(rs.code < 200 && rs.code > 299) {
				throw new Exception("Failed to process stream url. Status code: "~to!string(rs.code));
			}
			// if("icy-metaint" !in rs.responseHeaders ){
				// return meta;
			// }
			string shift = rs.responseHeaders["icy-metaint"];
			writeln("Shift: "~ shift);
			ulong metaShift = to!ulong(shift);
			
			auto stream = rs.receiveAsRange();        			
			
			while(!stream.empty) {                        
			
				ulong curLen = rs.contentReceived;         
				
				if(curLen > metaShift){
					
					ulong skip = rs.contentReceived - metaShift;
					ulong start = stream.front.length - skip;

					//writeln("start: "~to!string(start)~". metaShift: "~to!string(metaShift)~ ". curLen: "~to!string(+curLen)~".");

					meta = extractMeta(start, stream.front);
					break;
				} else {
					stream.popFront;
					//writefln("Received %d bytes, total received %d from document length %d", stream.front.length, rs.contentReceived, rs.contentLength);                            
				}         
			}
		}catch(Error e){
			writefln("ERROR: "~to!string(e));
		}

        //writefln(meta);
        return meta;
    
    }

    string extractMeta(ulong start, ubyte[] data){                
        char[] meta;
        char ch;
        for(ulong i = start; i < data.length; i++){
            ch = data[i];
            if(ch != ';'){
                meta~=ch;
            } else {       
                return to!string(meta);
            }
        }
        return "";
    }     
}


void main() {
	string[] urls = ["http://23263.live.streamtheworld.com/KLYYFMAAC.aac", "https://27243.live.streamtheworld.com/KDLDFMAAC.aac"];	

    Scanner scanner = new Scanner();

    for(int i =0; i < 100; i++){
        foreach(url; urls){
            writeln("meta: "~scanner.getStreamMetadataPos(url));
        }
    }
}

```

**Comment by ikod** [comment]
Hello, @oracle1wr 

Here is what happens here(see explanation below):

> class Scanner {
> 	Request rq = Request();

You initialized Request once when you created Scanner instamce.

> 
>     string getStreamMetadataPos(string streamUrl){        
>         if(streamUrl.empty){
>             throw new Exception("Failed to scan empty Url!");
>         } 
> 
>         if(streamUrl.startsWith("https:")){
>             streamUrl = "http://"~streamUrl[8..$];
>         } else if(!streamUrl.startsWith("http:")){
>             streamUrl = "http://"~streamUrl;
>         }
>         string meta;
>         //rq.clearHeaders;
> 		try { 			
> 			//auto rq = Request();
**Note this your comment ^^^**
> 			rq.useStreaming = true;
> 			rq.verbosity = 0;
> 			rq.addHeaders(["Icy-MetaData": "1"]);
> 			rq.timeout(30.seconds);
> 			auto rs = rq.get(streamUrl);        

You stared receiving body

> 			if(rs.code < 200 && rs.code > 299) {
> 				throw new Exception("Failed to process stream url. Status code: "~to!string(rs.code));
> 			}
> 			// if("icy-metaint" !in rs.responseHeaders ){
> 				// return meta;
> 			// }
> 			string shift = rs.responseHeaders["icy-metaint"];
> 			writeln("Shift: "~ shift);
> 			ulong metaShift = to!ulong(shift);
> 			
> 			auto stream = rs.receiveAsRange();        			
> 			
> 			while(!stream.empty) {                        
> 			
> 				ulong curLen = rs.contentReceived;         
> 				
> 				if(curLen > metaShift){
> 					
> 					ulong skip = rs.contentReceived - metaShift;
> 					ulong start = stream.front.length - skip;
> 
> 					//writeln("start: "~to!string(start)~". metaShift: "~to!string(metaShift)~ ". curLen: "~to!string(+curLen)~".");
> 
> 					meta = extractMeta(start, stream.front);
> 					break;

Then you break in the middle of receiving response body. At this point you leave `Request` in the state when it have opened connection and continue to receive response.

> 				} else {
> 					stream.popFront;
> 					//writefln("Received %d bytes, total received %d from document length %d", stream.front.length, rs.contentReceived, rs.contentLength);                            
> 				}         
> 			}

> 
> void main() {
> 	string[] urls = ["http://23263.live.streamtheworld.com/KLYYFMAAC.aac", "https://27243.live.streamtheworld.com/KDLDFMAAC.aac"];	
> 
>     Scanner scanner = new Scanner();
> 
>     for(int i =0; i < 100; i++){
>         foreach(url; urls){
>             writeln("meta: "~scanner.getStreamMetadataPos(url));

at this point you request new url, but stream not closed and everything get messed.
Current workaround is to uncomment your own comment above. Why it didn't work for you?

>         }
>     }
> }
> ```

I should reset Request struct when new `get` call arrive, and it seems to me that I did it. Will check

**Comment by oracle1wr** [comment]
Hello @ikod,
Ok, it makes sense, but is there a way to reset a request and close connection? So it would allow to reuse request.

The main reason why I started looking towards a single request instance is because of memory leak, it is not huge, but in my case I have thousands call s in a minute. And it created quite significant impact over time.

Thank you!

**Comment by ikod** [comment]
> Hello @ikod, Ok, it makes sense, but is there a way to reset a request and close connection? So it would allow to reuse request.
> 
> The main reason why I started looking towards a single request instance is because of memory leak, it is not huge, but in my case I have thousands calls in a minute. And it created quite significant impact over time.
> 
> A leak may be also related to streams/connections are not closed, even though Request itself is no longer in use and can be collected by GC.
> 
> Thank you!

This shoud be done if you issue a new call to `get` while stream is not closed. I wil check and fix it.
So if you uncomment `rq = Request()` you get memory inflation?

**Comment by oracle1wr** [comment]
>> So if you uncomment rq = Request() you get memory inflation?
That's correct.

**Comment by ikod** [comment]
Well, `rq = Request()` actually close connection, clear buffers and everything else... It do not call some explicit memory `free()` as we use GC language. You can try to call GC.collect() after every iteration (if you don't already call it.

**Comment by ikod** [comment]
> Well, `rq = Request()` actually close connection, clear buffers and everything else... It do not call some explicit memory `free()` as we use GC language. You can try to call GC.collect() after every iteration (if you don't already call it.

To be clear: assignment `rq = Request()` do not create new instance it reinitialize old request instance.

**Comment by oracle1wr** [comment]
ok, got you. 
I tried GC.collect - didn't help.

Will get more details to demonstrate of what I'm observing.
Going forward will stick to new Request() for every outgoing request.

Thank you!

**Comment by oracle1wr** [comment]
No leaks detected. I run it several days everything is within expected limits. So, confirming, memory inflation was not related to Request.
Thank you for your effort. 
Closing this issue.
