### ISSUE TITLE
WTH has happened?

### ISSUE THREAD

**Issue by Aphexus** [ikod/dlang-requests#160]
requests used to be self contained but had some depreciated features(using body, ex) but when I try to upgrade it seems there are some major changes such as using cachemem which uses automem and these changes seem to not be consistent(ikod.containers vs containers).

Now my old package is broke and it seems like a mess trying to figure out what it is.  ;/

**Comment by ikod** [comment]
Hello,

Which versions do you use?

**Comment by ikod** [comment]
Please feel free to reopen issue
