### ISSUE TITLE
It should provide a way to pass non-unique params

### ISSUE THREAD

**Issue by trikko** [ikod/dlang-requests#18]
Query params could be not unique. For example this is a valid way to pass an array:

http://example.com?name[]=hello&name[]=world

So an associative array string[string] can't handle this case.

Check this:

```d
alias QueryParam = Tuple!(string, "key", string, "value");

auto queryParams(T...)(T params)
{
   static assert (T.length % 2 == 0, "wrong args count");

   QueryParam[] output;
   output.reserve = T.length / 2;

   void queryParamsHelper(T...)(T params, ref QueryParam[] output)
   {
      static if (T.length > 0)
      {
         output ~= QueryParam(params[0].to!string, params[1].to!string);
         queryParamsHelper(params[2..$], output);
      }
   }

   queryParamsHelper(params, output);
   return output;
}
```

So you can write:

```d
rs = rq.get("http://httpbin.org/get", queryParams("name[]", "first", "name[]", "another"));
```

but also:

```d
// Automagic to!string
rs = rq.get("http://httpbin.org/get", queryParams("number", 3, "hello", "world"));
```

**Comment by ikod** [comment]
Hello,
Thfnks, will look at this.

**Comment by ikod** [comment]
I commited changes:
```
void main() {
    writeln(getContent("http://httpbin.org/get", queryParams("number", 3, "hello", "world")));
}

{
  "args": {
    "hello": "world",
    "number": "3"
  },
  "headers": {
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "dlang-requests"
  },
  "origin": "74.71.212.138",
  "url": "http://httpbin.org/get?number=3&hello=world"
}
```
What is not very good - parameter "number" on client side coded and on server side recognized as string. Probably I'll fix this a bit later.
Thanks for this issue.

**Comment by wilzbach** [comment]
> queryParams("number", 3, "hello", "world")

What about using D`s variadic features?

```
getContent("foo.com", "arg1", param1, "arg2", param2)
``

With CTFE constraints you can ensure that nothing is wrong.

This pattern is also used by std.getopt
https://dlang.org/phobos/std_getopt.html

**Comment by trikko** [comment]
@ikod: I don't think there's any difference on server side. I think it can get only strings from query parameters.

@wilzbach: but it become difficult if you need to build query parameters and then you want to call getContent(). Using my way you can build and pass a QueryParam[] you filled in advance.

**Comment by wilzbach** [comment]
> but it become difficult if you need to build query parameters and then you want to call getContent().

1) Yes but we can simply support both and make a convenient API?
2) Isn't appending to a tuple also difficult/impossible?

@ikod are you sure it works with nun-unique keys - I still see

```
 HTTPResponse exec(string method="GET")(string url = null, string[string] params = null) if (method != "POST")
    {
```

**Comment by ikod** [comment]
@wilzbach 
I will try to use internally something like
Tuple!(string, "name", Algebraic!(string, int, float))

From what I pushed:
```
    HTTPResponse exec(string method="GET")(string url, string[string] params) {
        return exec!method(url, params.byKeyValue.map!(p => QueryParam(p.key, p.value)).array);
    }
.....
    HTTPResponse exec(string method="GET")(string url = null, QueryParam[] params = null) {
.....
```

**Comment by ikod** [comment]
Oops, sorry this really doesn't matter for param to be string or int or whatever

**Comment by ikod** [comment]
> What about using D`s variadic features?
> 
> getContent("foo.com", "arg1", param1, "arg2", param2)
> 
Looks like for getContent I can add variadic function.

**Comment by trikko** [comment]
@wilzbach: 
1) Yes if it doesn't add confusion
2) It's quite easy. You should actually use an array of tuple so:

```d
alias QueryParam = Tuple!(string, "key", string, "world");
QueryParam[] params;

if (...)
params ~= QueryParam("hello", "world");

if (...)
params ~= QueryParam("other", "123");

getContent(..., params);
```

We can also define QueryParam as struct with a template ctor   QueryParam(T)(string key, T value) that stores _value = value.to!string;

**Comment by ikod** [comment]
Hello,
done
```
    string name = "user", sex = "male";
    int    age = 42;
    r = getContent("https://httpbin.org/get", "name", name, "age", age, "sex", sex);
```
If you find some dirty code - please fill free to send any notes.

**Comment by trikko** [comment]
How do you write the code in my last comment?

**Comment by ikod** [comment]
@trikko no, I placed code
<img width="655" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1273417/15682559/4a81e2ac-272c-11e6-8dcb-9de5f25ee4f6.png">
 in separate reply....

**Comment by ikod** [comment]
Hello @trikko ,
Can I close this issue?
