### ISSUE TITLE
adders  do not compatible with protocol

### ISSUE THREAD

**Issue by bubnenkoff** [ikod/dlang-requests#2]
Why I am getting this?

http://img.ctrlv.in/img/16/04/24/571d1d81e8568.png

**Comment by ikod** [comment]
maybe this is because your localhost resolve to ipv6 and ipv4 address. Attempt to connect on ipv6 address fails and after that ipv4 used.
Maybe this should be reported as Warning, not Error.
Please do not close this issue, I have to find correct solution.
