### ISSUE TITLE
creation folders on FTP

### ISSUE THREAD

**Issue by bubnenkoff** [ikod/dlang-requests#26]
need way to create folder on FTP and check if folder on FTP is exists (if it's possible)

**Comment by bubnenkoff** [comment]
And please add FTP usage example

**Comment by bubnenkoff** [comment]
It's seems that change on ftp do not supported. If yes, it should be example for it too.

**Comment by bubnenkoff** [comment]
Вообще бы еще примеров побольше, а то даже как логиниться не совсем понятно. В коде фрагмент вижу про это, но как использовать не совсем ясно.

**Comment by ikod** [comment]
Need fix for recursive directory test/creation.

**Comment by ikod** [comment]
Attempt to create folders recursively
