### ISSUE TITLE
Failed to connect to localhost:8529([::1]:8529)

### ISSUE THREAD

**Issue by bubnenkoff** [ikod/dlang-requests#3]
http://img.ctrlv.in/img/16/05/02/572730a71b73d.png

**Comment by ikod** [comment]
а на порту 8259 на ipv6 адресе какой-то сервер слушает? Похоже что нет, что
только на ipv4

2016-05-02 13:49 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
да, по идее только ipv4.

**Comment by ikod** [comment]
тогда это просто информационное сообщение, в последних версиях оно
выводится как warning

                warningf("Failed to connect to %s:%d(%s): %s", host, port,
a, e.msg);
наверное есть смысл поставить уровень в error:

    globalLogLevel(LogLevel.error);


2016-05-02 17:34 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
А у тебя вообще нет идей откуда этот
 globalLogLevel(LogLevel.error); 
вылезает и почему это нужно везде указывать. Просто первый раз с таким сталкиваюсь. Может в коде можно что-то поменять?
