### ISSUE TITLE
It gives a lot of linker errors

### ISSUE THREAD

**Issue by erdemoncel** [ikod/dlang-requests#32]
When I try to compile simple example it gives a lot of linker errors.

> dmd  -I/home//dlang/import -L-L/home//dlang/lib -L-l:libhtmld.a -L-l:librequests.a test.d -oftest
> /home//dlang/lib/librequests.a(streams.o): In function `_D8requests7streams19_sharedStaticCtor45FZv':
> streams.d:778: undefined reference to `SSL_library_init'
> streams.d:779: undefined reference to `OpenSSL_add_all_ciphers'
> streams.d:780: undefined reference to `OpenSSL_add_all_digests'
> streams.d:781: undefined reference to `SSL_load_error_strings'
> /home//dlang/lib/librequests.a(streams_3be_52d.o): In function `_D8requests7streams13OpenSslSocket7initSslMFS8requests7streams10SSLOptionsZv':
> streams.d:795: undefined reference to `TLSv1_client_method'
> streams.d:795: undefined reference to `SSL_CTX_new'
> streams.d:798: undefined reference to `SSL_CTX_set_default_verify_paths'
> streams.d:800: undefined reference to `SSL_CTX_load_verify_locations'
> streams.d:802: undefined reference to `SSL_CTX_set_verify'
> streams.d:810: undefined reference to `SSL_CTX_use_PrivateKey_file'
> streams.d:811: undefined reference to `SSL_CTX_use_certificate_file'
> streams.d:814: undefined reference to `SSL_CTX_use_PrivateKey_file'
> streams.d:815: undefined reference to `SSL_CTX_use_certificate_file'
> streams.d:818: undefined reference to `SSL_CTX_use_PrivateKey_file'
> streams.d:819: undefined reference to `SSL_CTX_use_certificate_file'
> streams.d:826: undefined reference to `SSL_new'
> streams.d:826: undefined reference to `SSL_set_fd'
> /home//dlang/lib/librequests.a(streams_3be_52d.o): In function `_D8requests7streams13OpenSslSocket7connectMFNeC3std6socket7AddressZv':
> streams.d:833: undefined reference to `SSL_connect'
> streams.d:834: undefined reference to `ERR_get_error'
> streams.d:834: undefined reference to `ERR_reason_error_string'
> /home//dlang/lib/librequests.a(streams_3be_52d.o): In function `_D8requests7streams13OpenSslSocket4sendMFNeAxvE3std6socket11SocketFlagsZi':
> streams.d:840: undefined reference to `SSL_write'
> /home//dlang/lib/librequests.a(streams_3be_52d.o): In function `_D8requests7streams13OpenSslSocket7receiveMFNeAvE3std6socket11SocketFlagsZi':
> streams.d:847: undefined reference to `SSL_read'
> /home//dlang/lib/librequests.a(streams_3be_52d.o): In function `_D8requests7streams13OpenSslSocket6__dtorMFZv':
> streams.d:866: undefined reference to `SSL_free'
> streams.d:866: undefined reference to `SSL_CTX_free'
> collect2: error: ld returned 1 exit status
> Error: linker exited with status 1
> make: *** [test] Error 1
> 
> Compilation exited abnormally with code 2 at Sat Dec  3 23:24:20

**Comment by ikod** [comment]
Hello,

looks like you have to link also with libssl and libcrypto

2016-12-03 22:37 GMT+02:00 Erdem <notifications@github.com>:

**Comment by erdemoncel** [comment]
Hello,

Linking with libssl solved the problem. 

Thanks.
