### ISSUE TITLE
Ftp requests fail if user name contains @ sign

### ISSUE THREAD

**Issue by erdemoncel** [ikod/dlang-requests#33]
```
import std.stdio;
import requests;

void main() {
    auto rq = Request();
    rq.verbosity = 3;
    auto f = File("test.txt", "rb");
    auto rs = rq.post("ftp://login:password@example.com/test.txt", f.byChunk(1024));
    writeln(rs.code);
    rs = rq.get("ftp://login:password@example.com/test.txt");
    writeln(rs.code);
}
```

Consider this example. If login name is like that user@site.com ftp requests fail with this exception.
 
> std.conv.ConvException@/usr/include/dmd/phobos/std/conv.d(2083): Unexpected 'a' when converting from type string to type uint
> ----------------
> ??:? pure @safe uint std.conv.parse!(uint, immutable(char)[]).parse(ref immutable(char)[]) [0x81b4fce]
> ??:? pure @safe ushort std.conv.parse!(ushort, immutable(char)[]).parse(ref immutable(char)[]) [0x81d4880]
> ??:? pure @safe ushort std.conv.toImpl!(ushort, immutable(char)[]).toImpl(immutable(char)[]) [0x81d48fc]
> ??:? pure @safe ushort std.conv.to!(ushort).to!(immutable(char)[]).to(immutable(char)[]) [0x81d4865]
> ??:? pure @safe bool requests.uri.URI.uri_parse(immutable(char)[]) [0x81d9152]
> ??:? pure ref @safe requests.uri.URI requests.uri.URI.__ctor(immutable(char)[]) [0x81d8ea3]
> ??:? requests.base.Response requests.Request.post!(std.stdio.File.ByChunk).post(immutable(char)[], std.stdio.File.ByChunk) [0x818d340]
> ??:? void upload.uploadToServer() [0x8196bcb]
> ??:? _Dmain [0x818b763]
> ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x8210322]
> ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x821026c]
> ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x82102de]
> ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x821026c]
> ??:? _d_run_main [0x82101fe]
> ??:? main [0x818f073]
> ??:? __libc_start_main [0x6fd532]

Also I think specifying login and password in url is not a good choice. 

Erdem

**Comment by ikod** [comment]
Hello, @erdemoncel 

Thanks for report!

Specifying login/password in url for ftp is deprecated practice, but it is still in usage.
I'll check for bug in url parser, and probably will allow to attach login/password for ftp in the same way as for http.

**Comment by ikod** [comment]
Hello, @erdemoncel 

You can try to update dlang-requests to current git master with next changes in your code (use rq.authenticator):

```d
import std.stdio;
import requests;

void main() {
    auto rq = Request();
    rq.verbosity = 3;
    rq.authenticator = new BasicAuthentication("user", "passwd");
    auto f = File("test.txt", "rb");
    auto rs = rq.post("ftp://example.com/test.txt", f.byChunk(1024));
    writeln(rs.code);
    rs = rq.get("ftp://example.com/test.txt");
    writeln(rs.code);
}
```
Please inform me if it works for you. If yes, I'll make new release with fixes and new request pool feature.

Thanks.

**Comment by erdemoncel** [comment]
Ok. This also works for me. 

Thanks.
