### ISSUE TITLE
отличия от vibed

### ISSUE THREAD

**Issue by bubnenkoff** [ikod/dlang-requests#4]
Не мог бы рассказать, чем твой модуль от аналогичной реализации в vibed отличается. На сколько их стоит в одном проекте смешивать?

Возможно этим бы даже readme стоило дополнить.

**Comment by ikod** [comment]
Начал писать его, потому что ставить vibed ради нескольких вызовов "get" -
бессмыслено. У меня есть проект, в котором главную работу выполняет
долгоживущий демон, непрерывно отправляя десятки get запросов в секунду и
для меня очень важно что-бы память не текла. Пробовал vibed - текла память,
потом взял библиотеку curl, она вроде не текла, но всё-равно ела очень
много памяти. Кроме того curl довольно низкоуровневая, а я хотел иметь
нечто вроде питоновских requests.



2 мая 2016 г., 18:32 пользователь Dmitry Bubnenkov <notifications@github.com
