### ISSUE TITLE
1.0.0-dev roadmap

### ISSUE THREAD

**Issue by ikod** [ikod/dlang-requests#40]
Hello!

@wilzbach , here is roadmap for 1.0.0-dev:

1. Rewrite Buffer. Use struct for container, reduce allocations. - **already done**, wery good results. May break some applications as Buffer now use immutable(ubyte)[] instead ubyte[]
1. add high-level put,delete API using putContent, delContent and Request.put, Request.del - **already done**. Add handling "delete" request for FTP.
1. Find and mark *deprecated* duplicated API's like get(url, string[string]) and get(url, QueryParams[])
1. Write command-line utility like curl or wget to demonstrate API usage.

If anybody have any comments, additions, etc - you are welcome.

**Comment by bubnenkoff** [comment]
I wish to get dlang-requests in phobos instead of stupid curl. Is it's possible? I seen topic about curl deprecation, but did not understand what plans to use instead it.

**Comment by wilzbach** [comment]
> @wilzbach , here is roadmap for 1.0.0-dev:

Sounds awesome! It's great to heat such nice plans for the future.

> I wish to get dlang-requests in phobos instead of stupid curl. Is it's possible? 

Same here! You should start a NG thread and push for it!
However, from what I read so far I think the consensus is that `curl` in Phobos sucks, but there are no plans to remove or replace it.

> I seen topic about curl deprecation, but did not understand what plans to use instead it.

For reference, I think you are referring to this discussion:

http://forum.dlang.org/post/bgvnjlpwuizbzvuthjaf@forum.dlang.org

**Comment by wilzbach** [comment]
> but there are no plans to remove or replace it.

I think it should try to explain this in more details from what I learned over the past months:

1) There's no event library in Phobos. Sönke is trying to push for [`eventcore`](https://github.com/vibe-d/eventcore), but I don't expect this to be part of Phobos soon
2) There's the problem of SSL and that as the D community has as not many security experts, it's a risky undertaking to include SSL into Phobos and from what I heard is very, very unlikely to happen soon.
3) There's quite a huge resistance _against_ adding new stuff as new stuff should be _the best optimal solution _ in terms of API design, performance, implementation etc.  (have a look at the old & stalled PRs at Phobos for new experimental modules)
4) There's another force at play that is _against_ deprecating and removing old stuff as breaking users's code is a high target.

**Comment by ikod** [comment]
@bubnenkoff and @wilzbach , thanks for your interest for this library!

Re inclusion to std: @wilzbach - exactly. I hope to include some async-based features in the future and I'd like to use some async library (today - most likely eventcore), but using anything except (nonexistant) std.event or std.async is risky in terms of work and time investment.

And one more point is the same as for python requests:

[http://docs.python-requests.org/en/master/dev/philosophy/#standard-library](http://docs.python-requests.org/en/master/dev/philosophy/#standard-library)
> Standard Library?
Requests has no active plans to be included in the standard library. This decision has been discussed at length with Guido as well as numerous core developers.
Essentially, the standard library is where a library goes to die. It is appropriate for a module to be included when active development is no longer necessary.

Actually I see no problems to live outside of std space as long as community have list of recommended libraries with feature comparison.
