### ISSUE TITLE
no property 'proxy' for type 'Request'

### ISSUE THREAD

**Issue by relonger** [ikod/dlang-requests#42]
Proxy property documented but seems to be not implemented at all! Neither in master nor in dev-1.0.0 branch. 

Any plans to implement?

**Comment by ikod** [comment]
Hello,
You are rigth, proxy property acedentally missed for Request (but present for HTTPRequest).

Thanks for report, will fix in both branches soon.

**Comment by relonger** [comment]
Please, check one more thing:

You require proxy_url to be valid http url, like: `http://proxy.org:3128`
but it's quite common to specify proxy in a simple way, like `proxy.org:3128`. If you try to use such proxy url you'll get strange error: unknown case in final switch at http.d -> setupConnection():663. It's because of failed uri.uri_parse(_proxy). 

You should give correct understandable exception ("invalid proxy url"), or support short urls for proxies.

**Comment by relonger** [comment]
And... :)
When you use proxy you should ignore uri change on redirects. Because you connect to the proxy, not to the target uri.

Now in function
handleURLChange(in URI from, in URI to)
I see a warning: "Have to reopen stream, because of URI change" on every redirect. It closes connection and then reopens it again to the same proxy. That's seems to be not correct behavior.

**Comment by ikod** [comment]
Hello @relonger ,

Sorry for delay.
Proxy property added to Request structure.
Connection to proxy stay alive on redirects or on host/scheme/... change.
I'm not sure if it is good idea to allow proxy specification like proxy:3128
fixes merged to dev and master branches.

**Comment by relonger** [comment]
Thanks!
Short proxy url isn't necessary, but it's good idea to raise well-understandable exception in case of invalid url, not about "final switch ..."

**Comment by ikod** [comment]
Yes, fixed, it should be more clear what is wrong with proxy uri.
