### ISSUE TITLE
Request.addHeaders doesn't control for duplicated headers

### ISSUE THREAD

**Issue by relonger** [ikod/dlang-requests#43]
```dlang
        auto rq = Request();
        rq.addHeaders(["User-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"]);
```

produce following request:
```
> GET / HTTP/1.1
> Connection: Keep-Alive
> User-Agent: dlang-requests
> Accept-Encoding: gzip, deflate
> Host: www.intel.com
> User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

Added header should replace previous default one.

**Comment by relonger** [comment]
If use header 'User-Agent' it was overwritten correctly. So the fix should ignore header case when store it in _headers dictionary.

**Comment by ikod** [comment]
Thanks, will look into this problem.

**Comment by ikod** [comment]
Hello, @relonger 
Should be fixed

**Comment by relonger** [comment]
Great! May be if you do normalize do it strictly:
`toUpper(w[0..1]) ~ w[1..$]`
change to
`toUpper(w[0..1]) ~ toLower(w[1..$])` ?

**Comment by ikod** [comment]
Actually' I'd like to make them all lowercase.
