### ISSUE TITLE
Support http_proxy and https_proxy

### ISSUE THREAD

**Issue by BlackEdder** [ikod/dlang-requests#46]
Would it be possible to support environment variables for proxies? (http_proxy, https_proxy, ALL_PROXY). These variables are commonly used on unix-like systems to enable proxies.

**Comment by ikod** [comment]
I think it is possible. Will check later.
Thanks.

8 Май 2017 г. 5:45 пользователь "Edwin van Leeuwen" <
notifications@github.com> написал:

**Comment by ikod** [comment]
Hello, @BlackEdder ,

requested feature implemented in current master and 1.0.0-dev branches.
You can use http_proxy, https_proxy, all_proxy (as well as uppercase names).
