### ISSUE TITLE
postContent doesn't accept InputRange on a Request object

### ISSUE THREAD

**Issue by WebFreak001** [ikod/dlang-requests#48]
I want to get the response of postContent as input range so I am using a Request object with streaming on but then `postContent` doesn't allow an InputRange as argument

**Comment by ikod** [comment]
Hello,
Can you, please, write minimal code to reproduce problem?
Thanks!

2 Июл 2017 г. 22:16 пользователь "Jan Jurzitza" <notifications@github.com>
написал:

**Comment by WebFreak001** [comment]
```d
import std.stdio;

auto f = File("a.txt").byChunk(1024);
auto req = Request();
req.useStreaming = true;
auto ret = req.postContent("https://example.org", f, "application/binary");
```

```
app.d(10): Error: template requests.postContent cannot deduce function from argument types !()(Request, string, ByChunk, string), candidates are:
../../.dub/packages/requests-0.4.2/requests/source/requests/package.d(352,13):        requests.postContent(A...)(string url, A args)
```

**Comment by ikod** [comment]
Hello @WebFreak001 

the problem is that postContent do  not accept Request as argument - it create Request with defaults during the call:
```
public auto postContent(A...)(string url, A args) {
    auto rq = Request();
    auto rs = rq.post(url, args);
    return rs.responseBody;
}
```
What you waint is probably

```
    auto f = File("a.txt").byChunk(1024);
    auto req = Request();
    req.useStreaming = true;
    auto ret = req.post("https://example.org", f, "application/binary");
```
(please note **post** instead of **postContent**)
This should work. If something will go wrong with compile or execution for this case - let me know, will check.

**Comment by WebFreak001** [comment]
How can I know what functions accept a Request? The README doesn't contain any info for this and I think supporting Request for all functions documented in the README would be the most obvious.

I will check if it compiles later today

**Comment by ikod** [comment]
Hello,

> I think supporting Request for all functions documented in the README would be the most obvious.
There are several levels of API - most detailed (HTTPRequest, FTPRequest) and less detailed(getContent/postContent). It is impossible to support all functions on all levels.
