### ISSUE TITLE
Не получается отправить данные в ArangoDB

### ISSUE THREAD

**Issue by bubnenkoff** [ikod/dlang-requests#5]
Не могу разобраться как данные в БД отправить (ArangoDB).

вот такой запрос для CURL работает нормально:
`echo {"sdf":"dima"} | curl -X POST --data-binary @- --dump - http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers`

onlinetest - имя БД
sitetestanswers - коллекции

Делаю тоже самое с помощью твоего кода:
```
    string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers";
    res.writeJsonBody(`{"a":"b"}`);
    auto rq = Request();
    auto rs = rq.post(collectionUrl, `{"a":"b", "c":[1,2,3]}`, "application/json");
```

В итоге вообще никакого результата не получаю. 

В какую сторону копать то можно?

**Comment by ikod** [comment]
А если добавить verbosity и логгинга?

string collectionUrl = "
http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers
";
res.writeJsonBody(`{"a":"b"}`);
auto rq = Request();
rq.verbosity = 2;
globalLogLevel(LogLevel.trace);
auto rs = rq.post(collectionUrl, `{"a":"b", "c":[1,2,3]}`,
"application/json");


4 мая 2016 г., 14:01 пользователь Dmitry Bubnenkov <notifications@github.com

**Comment by bubnenkoff** [comment]
Что-то не пойму, что я не так делаю http://img.ctrlv.in/img/16/05/04/5729d9a8e4a52.png

**Comment by ikod** [comment]
Про логгинг - не знаю, можно убрать этот вызов setGobalLevel. Но вижу что
после закрывающей фигрурной скобки в json стоит пробел. Это может приводить
к проблеме

2016-05-04 14:15 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
http://img.ctrlv.in/img/16/05/04/5729dc9acba36.png

**Comment by ikod** [comment]
Не вижу никакого вывода по vrbose. Он должен был попасть в stdout -
отправленные и принятые заголовки как минимум.
Ну и я никогда не пробовал совмещать свою либу с vibed - он же берёт на
себя всё управление, может там и не запускается ничего. А почему не
использовать тогда уже клиента из vibed?

2016-05-04 14:27 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
я с ним туплю -- плохо понимаю его под в стиле:

```
		requestHTTP("http://localhost:8529/_db/testdb/_api/simple/by-example",
			(scope req) {
				req.method = HTTPMethod.PUT;
```

Твоя выглядит объективно проще. Не подскажешь как в нем запрос переслать на другой УРЛ?

`void questions(HTTPServerRequest req, HTTPServerResponse res)
{
 Json questions = req.json; // get request

 res.writeBody("Hello, World!", "text/plain");  // some answer to server

 string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers"; // вот сюда надо переслать


}
`

**Comment by bubnenkoff** [comment]
Короче вот как сделай. Если есть критика буду рад услышать:

```
void questions(HTTPServerRequest req, HTTPServerResponse res)
{
    Json questions = req.json;
 //  logInfo(questions.toString);
   string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers"; // вот сюда переслать запрос надо
    res.writeBody("Hello, World!", "text/plain");  // FIXME

    sendQuestionsToArangoDB(questions); // to ArangoDB
    
}


void sendQuestionsToArangoDB(Json questions)
{
    
    string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers"; // вот сюда переслать запрос надо

    requestHTTP(collectionUrl,
        (scope req) {
            req.method = HTTPMethod.POST;   
            req.writeJsonBody(questions);
        },
        (scope res) {
            logInfo("Response: %s", res.bodyReader.readAllUTF8());
        }
    );

    writeln("SENDED");

}

```

**Comment by ikod** [comment]
Ну вроде всё просто: rq.post принимает json в виде строки, то что нужно
отправить нужно превратить в строку и подставить в вызов post:
auto rs = rq,post(collectionUrl, stringwithjson, "application/json");

если добавлен verbosity то хоть какой-то вывод в stdout должен появиться

2016-05-04 14:40 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
```
void sendQuestionsToArangoDB(Json questions)
{
    
    string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers"; // вот сюда переслать запрос надо

    auto rq = Request();
    rq.verbosity = 2;
    auto rs = rq.post(collectionUrl, `{"a":"b", "c":[1,2,3]}`, "application/json");
 
    writeln("SENDED");

}
```
Вывод:



> POST /_db/onlinetest/_api/document/ HTTP/1.1
> Content-Length: 22
> Connection: Close
> Host: localhost:8529
> Content-Type: application/json
>
< HTTP/1.1 400 Bad Request
< Server: ArangoDB
< Connection: Close
< Content-Type: application/json; charset=utf-8
< Content-Length: 134
< 134 bytes of body received
SENDED


Все делаю по этой инструкции: https://docs.arangodb.com/HttpDocument/WorkingWithDocuments.html

**Comment by ikod** [comment]
Кажется знаю где может быть проблема. Через час смогу проверить.

2016-05-04 15:08 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
Отлично) жду)

**Comment by bubnenkoff** [comment]
Вот если что тему создал. Вдруг кто-то подскажет http://stackoverflow.com/questions/37027066/vibed-cant-send-data-to-arangodb-invalid-document-type

**Comment by ikod** [comment]
попробуй версию 0.1.0 - должно отработать. Если нет - снова присылай вывод

2016-05-04 15:52 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
О! В новой версии все работает! Спасибо!
