### ISSUE TITLE
Implement performing a HTTP requests using a specified interface.

### ISSUE THREAD

**Issue by japplegame** [ikod/dlang-requests#51]
It would be nice to be able to perform queries through a specific interface. For example, specifying its IP address.

**Comment by ikod** [comment]
ok, thanks! Will look into this.

Just several links to note for myself
https://github.com/curl/curl/blob/master/lib/if2ip.c
http://man7.org/linux/man-pages/man3/getifaddrs.3.html

**Comment by ikod** [comment]
Hello, @japplegame 

this feature implemented in latest version, so I'll close this issue. Feel free to reopen it in case of any problems with it.

**Comment by japplegame** [comment]
Many thanks. I'll test it later.
