### ISSUE TITLE
dlang-requests requere OpenSSL on http url

### ISSUE THREAD

**Issue by bubnenkoff** [ikod/dlang-requests#53]
```
import std.stdio;
import requests;
import std.file;

void main()
{
	Request rq = Request();
	Response rs = rq.get("http://geoserver.readthedocs.io/en/latest/_images/imagemosaiccreate1.png");
	File f = File("123.png", "w");
	f.write(rs.responseBody.data);

}
```
`object.Exception@requests-0.5.1\requests\source\requests\ssl_adapter.d(59): loading libssl: error 0 Program exited with code 1`

**Comment by ikod** [comment]
https://slproweb.com/products/Win32OpenSSL.html
Use Win32 OpenSSL v1.0.2L, when asked - agree to install in system directories.
this should fix problem.

**Comment by ikod** [comment]
hello, @bubnenkoff 

Please, confirm that problem fixed.

**Comment by bubnenkoff** [comment]
All works fine. There only should be:
`f.rawWrite(rs.responseBody.data);`
only `libssl32.dll` for Windows is required.
