### ISSUE TITLE
`requests.ssl_adapter.OpenSSL.OpenSSL_version_detect` is broken on armv7h

### ISSUE THREAD

**Issue by ghost91-** [ikod/dlang-requests#57]
Trying to use requests on my raspberry pi 3 using archlinux arm resultet in
```
object.Exception@../.dub/packages/requests-0.5.3/requests/source/requests/ssl_adapter.d(103): loading openssl: unknown version for init
```
Upon further investigation, I found out that `requests.ssl_adapter.OpenSSL.OpenSSL_version_detect` actually returns `Version(1, 65)`, which obviously is nonsense. Making the function always return `Version(1, 1)` fixed it for me (1.1 is the version that is installed).

**Comment by ghost91-** [comment]
I think the problem is the following: The return value of `OpenSSL_version_num()` is `unsigned long`. On x86_64 and x86 this usually is a 64 bit datatype, so using `long` as the data type in D would be correct (alothugh I suppose using `ulong` would be better?). However, on armv7h `unsigned long` is actually only a 32 bit datatype, so we need to use `int` (or better `uint`) in D. I already tried it and it worked on my raspberry pi 3.

**Comment by ikod** [comment]
Hello, @ghost91- 

Thanks for the report!

https://github.com/openssl/openssl/blob/master/include/openssl/crypto.h#L163 defines OpenSSL_version_num with return value type `unsigned long`, and https://manpages.debian.org/testing/libssl-doc/OpenSSL_version_num.3ssl.en.html and I think I have to follow this definition.

Can you please try to change line
```
long function() OpenSSL_version_num = cast(long function())DLSYM(cast(void*)_libssl, "OpenSSL_version_num".ptr);
```
to
```
ulong function() OpenSSL_version_num = cast(ulong function())DLSYM(cast(void*)_libssl, "OpenSSL_version_num".ptr);
```
and see if it helps?

Thanks in advance!

**Comment by ghost91-** [comment]
As mentioned in my earlier post, the correct way to do it would be
```D
uint function() OpenSSL_version_num = cast(uint function())DLSYM(cast(void*)_libssl, "OpenSSL_version_num".ptr);
```
because on ARM `unsigned long` is an 32 bit unsigned integer dataytype. So the correspoding datatype in D is `uint`.

I tried
```D
ulong function() OpenSSL_version_num = cast(ulong function())DLSYM(cast(void*)_libssl, "OpenSSL_version_num".ptr);
```
as you suggested, but the problem is the same as if one is using `long`. The reason that both `long` and `ulong` have the same behaviour is that the returnvalue of `OpenSSL_version_num` is something along the lines of `0x1010006f`, which also fits (positively) in a `long`.

On ARM, the return value of
```D
long function() OpenSSL_version_num = cast(long function())DLSYM(cast(void*)_libssl, "OpenSSL_version_num".ptr);
```
is something like ` 0xYYYYYYYY1010006f`, where `Y` are some random hexadecimal digits. It really is random, the return value is not always the same! So the low 32 bit are correct, but the high 32 bit are some random gibberish. This shows once more, that on ARM `uint` needs to be used. Of course on x86 and x86_64 `ulong` still needs to be used.

**Comment by ikod** [comment]
OK, thanks!

**Comment by ghost91-** [comment]
I am currently building my fix on a Raspberry Pi 1 (armv6h). If it also succeeds there, I'll create a pullrequest.

**Comment by ikod** [comment]
Can you please check that this patch fix problem (leaving ulong as rerturn type)

-            auto v = OpenSSL_version_num();
+            auto v = OpenSSL_version_num() & 0xffffffff;

**Comment by ghost91-** [comment]
Your patch (simply setting the high 32 bit 0) seems to work. However I still think that using version based compilation is the correct solution. The memory that is contained in the higher 32 nees to come from somewhere, and we don't know what it really contains. We don't modify it, so it should not be that much of a problem, but in some rare edge cases, it might create problems.

The build on the Raspberry Pi 1 (finally!!) completed and worked, too. I will create a pullrequest, in case I could convice you that my solution is the better one :D

**Comment by ikod** [comment]
there are two ponts here: 

https://manpages.debian.org/testing/libssl-doc/OpenSSL_version_num.3ssl.en.html
clearly states that return value type is unsigned long (probably it is the same on ARM)

NAME
OPENSSL_VERSION_NUMBER, OpenSSL_version, OpenSSL_version_num - get OpenSSL version number
SYNOPSIS
 #include <openssl/opensslv.h>
 #define OPENSSL_VERSION_NUMBER 0xnnnnnnnnnL
 #include <openssl/crypto.h>
 unsigned long OpenSSL_version_num();
 const char *OpenSSL_version(int t);

and at the same time it is obvious that only lower 32 bits of data used to store version info:
 `MNNFFPPS: major minor fix patch status`

I'd like to avoid conflict with openssl library definition and I don't see a reason for it if I can do this in clear and legal way.

Anyway, thanks a lot for your report and investigation, I'll roll out release with fix in few days.

**Comment by ghost91-** [comment]
When using `uint` on ARM, there is no conflict with the openssel library definition. That is my point. It's true, that on ARM the return type of `OpenSSL_version_num` is also defined as `unsigned long`. But as I was trying to explain earlier, on ARM this is an unsigned 32 bit integer datatype (see http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0041c/ch03s02s02.html). The corresponding data type in D is `uint`, because the language specification defines this to be a 32bit unsigned integer datatype on all platforms.

**Comment by ikod** [comment]
Fix released, thanks!
