### ISSUE TITLE
Не получается отправить объект JSON

### ISSUE THREAD

**Issue by bubnenkoff** [ikod/dlang-requests#6]
```
void sendQuestionsToArangoDB(Json questions)
{
    string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers";
    auto rq = Request();
    rq.verbosity = 2;
    string s = `{"test":"some value111"}`;
    auto rs = rq.post(collectionUrl, s, "application/json");
    writeln(s);
    writeln("SENDED");


}
```
Стоит вместо: `s` отправить `questions`. Во первых не компилится:
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\requests-0.1.0\requests\source\requests\http.d(1212,27): Error: template requests.http.Request.exec cannot deduce function from argument types !("POST")(string, Json, string), candidates are:

Во вторых если в `to!string` сделать, то вылетает ошибка:

```
> POST /_db/onlinetest/_api/document/?collection=sitetestanswers HTTP/1.1
> Content-Length: 2941
> Connection: Close
> Host: localhost:8529
> Content-Type: application/json
>
< HTTP/1.1 400 Bad Request
< Server: ArangoDB
< Connection: Close
< Content-Type: application/json; charset=utf-8
< Content-Length: 80
< 80 bytes of body received
SENDED

```

**Comment by ikod** [comment]
нужно превратить Json  в строку. to!string может добавлять форматирование.
из какой библиотеки этот Json?

2016-05-04 17:06 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
из Vibed

**Comment by bubnenkoff** [comment]
да, он походу добавляет квадратные скобки. В начале и конце. Как от них избавиться покрасивее?

**Comment by ikod** [comment]
questions.toString() ?


2016-05-04 17:11 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
http://img.ctrlv.in/img/16/05/04/572a045bbef81.png

решил выкусить руками, не помогло

**Comment by bubnenkoff** [comment]
to!string и toString() вроде как вообще идентично работают.

**Comment by ikod** [comment]
трудно без кода понять. нужен код и вывод

2016-05-04 17:17 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
```
void questions(HTTPServerRequest req, HTTPServerResponse res)
{
    Json questions = req.json;
    res.writeBody("Hello, World!", "text/plain");  // FIXME

    sendVisitorInformationToArangoDB(req); // просто данные переслать сюда и вернуться

    runTask(toDelegate(&sendVisitorInformationToArangoDB), req);
    runTask(toDelegate(&sendQuestionsToArangoDB), questions);

}


void sendVisitorInformationToArangoDB(HTTPServerRequest req)  // только для тех кто прошел тест по идее. Нужно убедиться что только их инфа будет храниться
{
    // req.peer - IP as string
    string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=visitors"; 
}



void sendQuestionsToArangoDB(Json questions)
{
    
    string collectionUrl = "http://localhost:8529/_db/onlinetest/_api/document/?collection=sitetestanswers"; // вот сюда переслать запрос надо


    auto rq = Request();
    rq.verbosity = 2;
    string s = `{"test":"some value111"}`;
    auto rs = rq.post(collectionUrl, to!string(questions), "application/json");
    writeln(s);
    writeln;
    writeln(to!string(questions));
    writeln("SENDED");


}
```

вывод: http://img.ctrlv.in/img/16/05/04/572a045bbef81.png

**Comment by ikod** [comment]
такой код нормально трабатывает:
import std.stdio;
import vibe.d;
import requests.http;

shared static this()
{
        auto settings = new HTTPServerSettings;
        settings.port = 8080;
        settings.bindAddresses = ["::1", "127.0.0.1"];
        listenHTTP(settings, &hello);

        logInfo("Please open http://127.0.0.1:8080/ in your browser.");
}

void hello(HTTPServerRequest req, HTTPServerResponse res)
{
    res.writeBody("Hello, World!");
    string data = `{"a":"b","c":"d"}`;
    Json j = parseJson(data);
    auto rq = Request();
    auto rs = rq.post("http://httpbin.org/post", j.toString(),
"application/json");
    writeln(rs.responseBody);
}

$ run
Listening for requests on http://[::1]:8080/
Listening for requests on http://127.0.0.1:8080/
Please open http://127.0.0.1:8080/ in your browser.
{
  "args": {},
  "data": "{\"c\":\"d\",\"a\":\"b\"}",
  "files": {},
  "form": {},
  "headers": {
    "Content-Length": "17",
    "Content-Type": "application/json",
    "Host": "httpbin.org"
  },
  "json": {
    "a": "b",
    "c": "d"
  },
  "origin": "78.26.154.216",
  "url": "http://httpbin.org/post"
}


2016-05-04 17:26 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
А в чем я могу косячить то?

**Comment by ikod** [comment]
не вижу.. может распечатать тот json который он пытается отправить и тогда
что-то станет ясно

2016-05-04 18:58 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
В плане распечатать?
Вот он у меня что выводит https://gist.github.com/bubnenkoff/db3a7c181e57bc42933b1410903b4600

**Comment by bubnenkoff** [comment]
Просто все валидаторы говорят, что он JSON валиден только с квадратными скобками как у меня

**Comment by ikod** [comment]
да, валиден. У меня проходит с этим json. Пока нет идей в чем дело

4 мая 2016 г., 20:00 пользователь Dmitry Bubnenkov <notifications@github.com

**Comment by bubnenkoff** [comment]
А если мой вкорячить то не проходит? Ну тот который я вставил?

**Comment by ikod** [comment]
именно он проходит

2016-05-04 20:03 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
Есть чувство, что что-то не то с размером или вложенностью. Пока пытаюсь его сокращать и смотреть что будет.

**Comment by bubnenkoff** [comment]
C помощью curl тоже ошибка 
https://gist.github.com/bubnenkoff/d3e0bdc903ca21fabcd37b0ab23ca3fa

**Comment by bubnenkoff** [comment]
Во, смотри, до меня кажется дошло! `[]` означают массив. А его можно передавать только если у него есть ключ типа: `a: []`

**Comment by ikod** [comment]
трудно сказать, это видиммо специфика сервера. с простыми json отрабатывает?

4 мая 2016 г., 20:41 пользователь Dmitry Bubnenkov <notifications@github.com

**Comment by bubnenkoff** [comment]
C простым да, но я не могу понять где конец простоты. Просто блин. Меня
сейчас вообще любой вариант устроит который хоть как-то бы заработал. Вот
мой оригинальный JSON
https://gist.github.com/bubnenkoff/aaeaf49bcfff0cc505071c06c15ca983



4 мая 2016 г., 20:44 пользователь ikod <notifications@github.com> написал:

**Comment by bubnenkoff** [comment]
В итоге обрезал все по максимуму. Получилось вот это https://gist.github.com/bubnenkoff/980b0b3afe35b7128b0b7b929174476c

Возможно дальше можно порезать тоже. Упорно не работает

**Comment by bubnenkoff** [comment]
`void sendQuestionsToArangoDB(Json questions)
{
    string collectionUrl = "http://localhost:8529/_db/otest/_api/document/?collection=sitetestanswers"; 
    auto rq = Request();
    rq.verbosity = 2;
//    string s = `{"isEnabled":true,"MaxAllowedChoice":3,"id":1,"question":"Каков уровень Вашей организации?","NowSelected":0,"answers":[{"isDisabled":false,"isSelected":false,"id":1,"answer":"Федеральные органы исполнительной власти"},{"isDisabled":false,"isSelected":false,"id":2,"answer":"Региональные органы исполнительной власти"},{"isDisabled":false,"isSelected":false,"id":3,"answer":"Местные административные органы управления"},{"isDisabled":false,"isSelected":false,"id":4,"answer":"Некоммерческие организации"},{"isDisabled":false,"isSelected":false,"id":5,"answer":"Частное лицо"},{"isDisabled":false,"isSelected":false,"id":6,"answer":"Другое","isTextBox":true,"userTextInputValue":"ddddddddd"}]}`;
    string s = `{"id":1,"question":"вопрос?"},{"id":2,"question":"вава?","answers":["isDisabled":false}],"MaxAllowedChoice":2,"NowSelected":0}`;
   // auto rs = rq.post(collectionUrl, to!string(questions), "application/json");
    auto rs = rq.post(collectionUrl, s, "application/json");
    writeln(s);
    writeln;
    writeln(to!string(questions));
    writeln("SENDED");


}
`

Вот этот код не работает. Грешу теперь только на вложенность элементов.

**Comment by ikod** [comment]
там и скобки фигурные не сбалансированы и после = должна идти кавычка `

4 мая 2016 г., 21:28 пользователь Dmitry Bubnenkov <notifications@github.com

**Comment by bubnenkoff** [comment]
Не мог бы показать что не так, а то я уже не втыкаю. Валидаторы же говорят что он валиден.

Обрезал все до:

echo  {"id":1,"question":"вопрос?"},{"id":2} | curl -X POST --data-binary @- --dump - http://localhost:8529/_db/otest/_api/document/?collection=sitetestanswers

**Comment by bubnenkoff** [comment]
Не вставляется:
    string s = `{"id":"1","question":"вопрос?"},{"id":2}`;

Вставляется:
    string s = `{"id":"1","question":"вопрос?"}`;

%)

Нет идей почему так может быть то?

**Comment by ikod** [comment]
идея только одна - в строке должен быть валидный json (в первом варианте он
невалидный), если json валидный но не вставляется - смотреть логи сервера,
что он говорит об ошибке

2016-05-04 21:40 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
Не мог бы проверить еще раз примеры который я дал на http://stackoverflow.com/questions/37034311/arangodb-cant-send-request-with-curl

Просто ей богу замучался. У тебя вставляется, там у человека вставляется -- у меня не вставляется. Даже не знаю в какую сторону копать.

**Comment by ikod** [comment]
если говорить об этой картинке, можешь включить в curl побольше дебага,
что-бы ыидеть точно что именно он отправляет?

4 мая 2016 г., 23:45 пользователь Dmitry Bubnenkov <notifications@github.com

**Comment by ikod** [comment]
http://img.ctrlv.in/img/16/05/04/572a5d4335db6.png об этой картинке

5 мая 2016 г., 0:08 пользователь Igor Khasilev <igor.khasilev@gmail.com>
написал:

**Comment by bubnenkoff** [comment]
А как дебагг то включить в нем расширенный?

**Comment by ikod** [comment]
добавь cur ключ --verbose

2016-05-05 0:15 GMT+03:00 Dmitry Bubnenkov <notifications@github.com>:

**Comment by bubnenkoff** [comment]
Скажи, а тебя сильно напрягет, если я попрошу тебя ArangoDB поставить и с
ней проверить свою библиотеку. По идее там ее ставить пару кликов. БД
создать и в ней коллекцию.

Мне тут отписали, что такой запрос работает:  http://screencloud.net/v/l5fZ

Я к сожалению до компа только вечером доберусь

четверг, 5 мая 2016 г. пользователь ikod написал:

**Comment by bubnenkoff** [comment]
Скажи, а тебя сильно напрягет, если я попрошу тебя ArangoDB поставить и с
ней проверить свою библиотеку. По идее там ее ставить пару кликов. БД
создать и в ней коллекцию.

Мне тут отписали, что такой запрос работает:  http://screencloud.net/v/l5fZ



четверг, 5 мая 2016 г. пользователь ikod написал:

**Comment by bubnenkoff** [comment]
О, мне тут пример скинули. Кажись надо делать так:

Этот код успешно добавляет документ в коллекцию:
import std.stdio;
import requests.http;

void main(string[] args) {
    string collectionUrl = "
http://localhost:8529/_db/otest/_api/document?collection=sitetestanswers";

    auto rq = Request();
    rq.verbosity = 2;
    string s = `{"some_data":[{"id":1, "question":"aaa"},{"id":2,
"question":"bbb?"}]}`;
    auto rs = rq.post(collectionUrl, s, "application/json");
    writeln("SENDED");
}


Буду дома проверю


четверг, 5 мая 2016 г. пользователь Dmitry Bubnenkov написал:
