### ISSUE TITLE
Building x86_64 on windows failes with:

### ISSUE THREAD

**Issue by ArjanKn** [ikod/dlang-requests#61]
source\requests\streams.d(789,31): Error: function requests.ssl_adapter.OpenSSL.SSL_set_fd (SSL* ssl, int fd) const is not callable using argument types (SSL*, socket_t) immutable

changing the line 789 in streams.d from
```openssl.SSL_set_fd(ssl, this.handle);```
to
```openssl.SSL_set_fd(ssl, cast(int)this.handle);```
makes the error disappear...

**Comment by ikod** [comment]
Hello @ArjanKn 

Thanks for report, fix pushed to master.

Please confirm that everything is ok, I'll close issue.
