### ISSUE TITLE
ssl connect failed: tlsv1 alert protocol version

### ISSUE THREAD

**Issue by zorael** [ikod/dlang-requests#62]
Arch/Manjaro Linux, 64-bit. dmd is v2.0.77.0, dlang-requests is 0.5.4. The openssl package is version 1.1.0.g-1, and the openssl-1.0 package is 1.0.2.l-1.

Trying to `getContent` from `https://www.twitch.tv`:

    import requests;
    void main()
    {
            getContent("https://www.twitch.tv");
    }

Error printed:

    Running ./twitch-https
    2017-11-10T21:08:57.095:http.d:handleURLChange:746 Have to reopen stream, because of URI change
    object.Exception@../../../.dub/packages/requests-0.5.4/requests/source/requests/streams.d(796): ssl connect failed: tlsv1 alert protocol version
    ----------------
    ??:? @trusted void requests.streams.OpenSslSocket.connect(std.socket.Address) [0xd63c2dcd]
    ??:? requests.streams.SocketStream requests.streams.SocketStream.connect(immutable(char)[], ushort, core.time.Duration) [0xd63c3c23]
    ??:? requests.streams.SocketStream requests.streams.SSLSocketStream.connect(immutable(char)[], ushort, core.time.Duration) [0xd63c34aa]
    ??:? void requests.http.HTTPRequest.setupConnection() [0xd63a2b65]
    ??:? requests.http.HTTPResponse requests.http.HTTPRequest.exec!("GET").exec(immutable(char)[], std.typecons.Tuple!(immutable(char)[], "key", immutable(char)[], "value").Tuple[]) [0xd6395215]
    ??:? requests.http.HTTPResponse requests.http.HTTPRequest.get!().get() [0xd639505d]
    ??:? requests.base.Response requests.request.Request.get!().get(immutable(char)[]) [0xd6394fe4]
    ??:? ref requests.streams.Buffer!(ubyte).Buffer requests.getContent!().getContent(immutable(char)[]) [0xd6394e22]
    ??:? _Dmain [0xd638e023]
    Program exited with code 1`

**Comment by ikod** [comment]
Hello, @zorael 
Thanks, was able to reproduce.
looking into it

**Comment by ikod** [comment]
Hello, @zorael 

Can you please check current master?

**Comment by zorael** [comment]
It seems to work now, yes. Thanks
