### ISSUE TITLE
HTTP Status-Line Reason-Phrase not obligatory ?

### ISSUE THREAD

**Issue by ArjanKn** [ikod/dlang-requests#63]
https://github.com/ikod/dlang-requests/blob/977806d16c22605830351830fa29e034b66ed35c/source/requests/http.d#L593

Did not scrutinize the rfs 2616 spec but it seems the  Reason-Phrase is not obligatory  (anymore).
There are at least apache servers out there which send Status-Lines without it.

**`Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF`**
```
-if ( parsed.length >= 3 ) {
+if ( parsed.length >= 2 ) {
```
Makes the _response.code valuable again.

**Comment by ikod** [comment]
Hello @ArjanKn 

It's funny. Do you have any example of such sites?

Thanks,

**Comment by ArjanKn** [comment]
https://bz.apache.org/bugzilla/show_bug.cgi?id=54946
https://bz.apache.org/bugzilla/show_bug.cgi?id=60362
https://github.com/spring-projects/spring-boot/issues/6789
Not public accessible, but the above links could give some hints and pointers..

**Comment by ikod** [comment]
Thanks, @ArjanKn  !

Will test patch and commit, most likely, tomorrow.

**Comment by ikod** [comment]
Hello, @ArjanKn 

Fix pushed to master, I'll close this issue.

Thanks for report
