### ISSUE TITLE
No support for Internationalized Domain Name

### ISSUE THREAD

**Issue by zorael** [ikod/dlang-requests#65]
Arch/Manjaro 64-bit, dmd 2.077.0, dlang-requests 0.6.0.

This URL opens in a browser: http://registrera-domän.se

dlang-requests throws an Exception;

    Can't resolve name when connect to registrera-domän.se:443: getaddrinfo error: Name or service not known

**Comment by ikod** [comment]
Hi @zorael 
Thanks for report, such name must be converted to punycode before sending to network.
Will fix this (hopefully on weekends)

**Comment by ikod** [comment]
hi, @zorael 

Please check current master, it should work.  Now ```requests``` depends on ```idna``` package, which I have to wrote.

Please feel free to ping me if something wrong.

**Comment by zorael** [comment]
It works great, thanks!

Could you please expose `original_host`? I'm accessing `Response.finalURI` and I'm currently modifying `uri.d` like so:

    // uri.d:105
    mixin(Getter_Setter!string("scheme"));
    mixin(Getter_Setter!string("host"));
    mixin(Getter_Setter!string("original_host"));  // <--
    mixin(Getter_Setter!string("username"));

**Comment by ikod** [comment]
@zorael 

Do you really need Getter_Setter for original_host or just Getter (which I'd prefer)?

**Comment by ikod** [comment]
ok, commited

**Comment by zorael** [comment]
Thank you!
