### ISSUE TITLE
Problem with https on Ubuntu, if libssl-dev not installed

### ISSUE THREAD

**Issue by eresid** [ikod/dlang-requests#69]
Post and Get requests not working without installed libssl-dev. Maybe need add a correct error like "Please, install a libssl-dev library", etc...
![2018-03-06 17-45-41](https://user-images.githubusercontent.com/3881790/37167551-e91497f8-230a-11e8-90bd-155660c64548.png)

**Comment by ikod** [comment]
@eresid 

Should be resolved in last commit, check please
