### ISSUE TITLE
request outputs ssl info on stderr

### ISSUE THREAD

**Issue by ghost91-** [ikod/dlang-requests#71]
Currently, when using requests and requesting an https url, requests writes something like the following to stderr:
```
2018-04-15T12:32:14.753:ssl_adapter.d:_staticCtor36:66 will use libssl.so
2018-04-15T12:32:14.753:ssl_adapter.d:_staticCtor36:80 will use libcrypto.so
```
It seems that `tracef` is used to print those.
In my opinion, this output should not be there, as it is information the user of the library does not need (were those debug prints?).

**Comment by ikod** [comment]
Hello @ghost91- 

It prints from [here](https://github.com/ikod/dlang-requests/blob/master/source/requests/ssl_adapter.d#L66) using logger. Probably should be prepended by debug(requests).

Thanks for report, will fix today or tomorrow.

**Comment by ikod** [comment]
Hello, @ghost91- 

Please check, should be fixed in current release

**Comment by ghost91-** [comment]
Seems to work well now, thank you!
