### ISSUE TITLE
release new (working) version

### ISSUE THREAD

**Issue by wilzbach** [ikod/dlang-requests#8]
the current dub version doesn't compile due to the missing package.d - do you to release a new version so other people don't run into this issue?

**Comment by ikod** [comment]
Hello!

Please, try now.

Sorry for this stupid bug.

**Comment by wilzbach** [comment]
> Please, try now 0.1.3

Yup works, thanks a lot for the fast response 

> Sorry for this stupid bug.

Not a big deal, one can tell dub to use `~master` ;-)
