### ISSUE TITLE
Slow response time for some sites compared to std.net.curl

### ISSUE THREAD

**Issue by llJochemll** [ikod/dlang-requests#80]
While writing a CosmosDB client I noticed that the response time was higher than what I was getting in my browser and postman. When I used std.net.curl instead of requests the response time was what I expected.

Decided to do some testing comparing requests to std.net.curl, mosts sites gave similar results, but some took considerably longer with requests. The results (average response time of 50 requests, ran multiple times):

    ------------------------------
    Testing https://www.amazon.com
      Requests: 578 ms, 725 ╬╝s, and 2 hnsecs
      std.net.curl: 128 ms, 480 ╬╝s, and 6 hnsecs
    ------------------------------
    ------------------------------
    Testing https://google.com
      Requests: 389 ms, 220 ╬╝s, and 7 hnsecs
      std.net.curl: 80 ms, 434 ╬╝s, and 3 hnsecs
    ------------------------------
    ------------------------------
    Testing https://bing.com/
      Requests: 481 ms and 112 ╬╝s
      std.net.curl: 129 ms, 860 ╬╝s, and 9 hnsecs
    ------------------------------
    ------------------------------
    Testing https://fcb7741c-0ee0-4-231-b9ee.documents.azure.com
      Requests: 293 ms, 436 ╬╝s, and 4 hnsecs
      std.net.curl: 45 ms, 54 ╬╝s, and 7 hnsecs
    ------------------------------

code:

    import requests;
    import std.net.curl;
    import std.datetime;
    import std.stdio;

    void main() {
        auto sites = [
            "https://www.amazon.com",
            "https://google.com",
            "https://bing.com/",
            "https://fcb7741c-0ee0-4-231-b9ee.documents.azure.com"
        ];
        
        foreach (site; sites) {
            writeln("------------------------------");
            writeln("Testing ", site);
            testRequests(site, 50);
            testCurl(site, 50);
            writeln("------------------------------");
        }
    }

    void testRequests(string url, int iterations) {
        auto req = Request();
        req.sslSetCaCert("ca.pem");
        req.keepAlive = true;

        auto start = Clock.currTime;
        foreach (i; 0..iterations) {
            req.get(url);
        }
        writeln("  Requests: ", (Clock.currTime - start) / iterations);
    }

    void testCurl(string url, int iterations) {
        auto http = HTTP(url);
        http.caInfo("ca.pem");
        http.addRequestHeader("Connection", "Keep-Alive");
        http.onReceiveHeader = (in char[] key, in char[] value) {};
        http.onReceive = (ubyte[] data) { return data.length; };

        auto start = Clock.currTime;
        foreach (i; 0..iterations) {
            http.perform();
        }
        writeln("  std.net.curl: ", (Clock.currTime - start) / iterations);
    }
dub.json:

    {
        "name": "testd",
	    "dependencies": {
	        "requests": "~>0.8.3"
	    }
    }

Tested with `dub run --compiler=dmd -a=x86_mscoff -b=plain` on a Windows 10 64bit PC (also some limited testing on a VM running in azure)

When I used verbose, I saw that the connection time had the largest impact on the request to CosmosDB and that each request had about the same connection time, even though keep-alive is used.

**Comment by ikod** [comment]
Hello @llJochemll 

I think that problem can be in 
`req.keepAlive = true;`

Can you, please, try to run your tests with

`req.keepAlive = false;`

**Comment by ikod** [comment]
Hello @llJochemll 

looking into your tests

**Comment by llJochemll** [comment]
Results with `req.keepAlive = false;`

    ------------------------------
    Testing https://www.amazon.com
      Requests: 382 ms, 727 ╬╝s, and 5 hnsecs
      std.net.curl: 139 ms, 683 ╬╝s, and 1 hnsec
    ------------------------------
    ------------------------------
    Testing https://google.com
      Requests: 463 ms, 873 ╬╝s, and 2 hnsecs
      std.net.curl: 73 ms, 449 ╬╝s, and 9 hnsecs
    ------------------------------
    ------------------------------
    Testing https://bing.com/
      Requests: 479 ms, 550 ╬╝s, and 7 hnsecs
      std.net.curl: 135 ms, 338 ╬╝s, and 6 hnsecs
    ------------------------------
    ------------------------------
    Testing https://fcb7741c-0ee0-4-231-b9ee.documents.azure.com
      Requests: 216 ms, 503 ╬╝s, and 5 hnsecs
      std.net.curl: 43 ms, 818 ╬╝s, and 5 hnsecs
     ------------------------------

**Comment by ikod** [comment]
Ok, keep-alive this was bad idea, I'm trying to run tests from the stable internet site

**Comment by ikod** [comment]
Hello @llJochemll 
Ok, when running tests with iterations = 1  I get
```
------------------------------
Testing https://www.amazon.com
  Requests: 538 ms, 252 μs, and 5 hnsecs
  std.net.curl: 39 ms, 312 μs, and 4 hnsecs
------------------------------
------------------------------
Testing https://google.com
  Requests: 1 sec, 690 ms, 166 μs, and 5 hnsecs
  std.net.curl: 1 sec, 724 ms, 609 μs, and 2 hnsecs
------------------------------
------------------------------
Testing https://bing.com/
  Requests: 109 ms, 972 μs, and 5 hnsecs
  std.net.curl: 128 ms, 667 μs, and 8 hnsecs
------------------------------
------------------------------
Testing https://fcb7741c-0ee0-4-231-b9ee.documents.azure.com
  Requests: 383 ms, 148 μs, and 3 hnsecs
  std.net.curl: 347 ms, 387 μs, and 3 hnsecs
------------------------------
```
which looks more or less the same.
My current theory is that problem is in ssl renegotiation. Need some time to check and fix.

Thanks for your report.

**Comment by llJochemll** [comment]
Booted up a sample site (http://test-requests.azurewebsites.net) with and without tls, and while the non-tls version loads faster, it still isn't as fast as expected (again 50 iterations):

    ------------------------------
    Testing http://test-requests.azurewebsites.net
      Requests: 107 ms, 13 ╬╝s, and 6 hnsecs
      std.net.curl: 30 ms, 78 ╬╝s, and 5 hnsecs
    ------------------------------
    ------------------------------
    Testing https://test-requests.azurewebsites.net
      Requests: 221 ms, 618 ╬╝s, and 6 hnsecs
      std.net.curl: 46 ms, 169 ╬╝s, and 4 hnsecs
    ------------------------------

**Comment by ikod** [comment]
Hello @llJochemll 

Ok, found sources of the problems.
1. www.amazon.com response headers contains:
```
< Connection: keep-alive
< Connection: Transfer-Encoding
```
curl ignore this, but dlang-requests handle this probably incorrect. I'll fix it.
2. google.com
```
* Connected to google.com (216.58.215.78) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: ca.pem
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
*        subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.google.com
*        start date: 2018-07-24 16:08:25 GMT
*        expire date: 2018-10-02 16:00:00 GMT
*        subjectAltName: google.com matched
*        issuer: C=US; O=Google Trust Services; CN=Google Internet Authority G3
*        SSL certificate verify ok.
> GET / HTTP/1.1
User-Agent: Phobos-std.net.curl/2.081 (libcurl/7.38.0)
Host: google.com
Accept: */*
Connection: Keep-Alive

< HTTP/1.1 301 Moved Permanently
< Location: https://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 02 Aug 2018 18:02:10 GMT
< Expires: Sat, 01 Sep 2018 18:02:10 GMT
< Cache-Control: public, max-age=2592000
* Server gws is not blacklisted
< Server: gws
< Content-Length: 220
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
< 
* Ignoring the response-body
* Connection #0 to host google.com left intact
```
libcurl left original connection to `google.com (216.58.215.78) port 443` intact while connecting to redirected location `www.google.com` (it is on different ip).
dlang-requests just close first connection to google.com and open new one to www.google.com. This is not optimal.

3. bing.com - same problem as with google.com (close connection to original site because of 302 redirect)
4. fcb7741c-0ee0-4-231-b9ee.documents.azure.com. - dlang requests close the connection because there is no Connection header in response. This is dlang requests bug, as HTTP 1.1 do not require this:

```
HTTP/1.1 defines the "close" connection option for the sender to signal that the connection will be closed after completion of the response. For example,

       Connection: close
in either the request or the response header fields indicates that the connection SHOULD NOT be considered `persistent' (section 8.1) after the current request/response is complete.


HTTP/1.1 applications that do not support persistent connections MUST include the "close" connection option in every message.
```

It is easy to fix 1 and 4, I'll fix it in few days.
Cases 2 and 3 are more difficult to fix, It can take a week or so.

Thanks a lot for your bug report!

**Comment by llJochemll** [comment]
Thanks for looking into it so fast!

**Comment by ikod** [comment]
The story with Amazon is more interesting:

```
root@ops1-3:~# curl -o- https://www.amazon.com/ 2>/dev/null | wc -l
109
root@ops1-3:~# curl -o- https://www.amazon.com/ 2>/dev/null | wc -l
109
root@ops1-3:~# curl -o- https://www.amazon.com/ 2>/dev/null | wc -l
109
root@ops1-3:~# curl -o- https://www.amazon.com/ 2>/dev/null | wc -l
109
root@ops1-3:~# curl -o- https://www.amazon.com/ 2>/dev/null | wc -l
4969
root@ops1-3:~# curl -o- https://www.amazon.com/ 2>/dev/null | wc -l
109
root@ops1-3:~# wget  -O- https://www.amazon.com/ 2>/dev/null | wc -l
4964
root@ops1-3:~# wget  -O- https://www.amazon.com/ 2>/dev/null | wc -l
2717
root@ops1-3:~# wget  -O- https://www.amazon.com/ 2>/dev/null | wc -l
4964
root@ops1-3:~# wget  -O- https://www.amazon.com/ 2>/dev/null | wc -l
4964
root@ops1-3:~# wget  -O- https://www.amazon.com/ 2>/dev/null | wc -l
4964
```
So Amazon (or Cloudflare) send short custom response for curl and long, human-readable response for other user-agents.

If I mimic requests for curl, then we are on par:
```
$ ./issue80 
------------------------------
Testing https://www.amazon.com
  Requests: 1 sec, 29 ms, 803 μs, and 7 hnsecs
  std.net.curl: 1 sec, 23 ms, 858 μs, and 1 hnsec
------------------------------

```
So actually this not a requests bug.

I'm also fixed problem with azure.
Moving forward.

**Comment by ikod** [comment]
Hello @llJochemll 

This is just short note. Things are moving forward:
```
------------------------------
Testing https://www.amazon.com
  std.net.curl: 1 sec, 159 ms, 635 μs, and 4 hnsecs
  Requests: 590 ms and 793 μs
------------------------------
------------------------------
Testing https://google.com
  std.net.curl: 411 ms, 553 μs, and 2 hnsecs
  Requests: 416 ms, 290 μs, and 4 hnsecs
------------------------------
------------------------------
Testing https://bing.com/
  std.net.curl: 622 ms and 349 μs
  Requests: 499 ms, 889 μs, and 6 hnsecs
------------------------------
```
but as it was quite large rewrite, I need some heavy testing.

**Comment by ikod** [comment]
Hello @llJochemll 
Here is my current results:
```
------------------------------
Testing https://www.amazon.com
  Requests: 624 ms, 368 μs, and 5 hnsecs
  std.net.curl: 190 ms, 284 μs, and 5 hnsecs
------------------------------
------------------------------
Testing https://google.com
  Requests: 93 ms, 707 μs, and 1 hnsec
  std.net.curl: 145 ms, 680 μs, and 3 hnsecs
------------------------------
------------------------------
Testing https://bing.com/
  Requests: 359 ms and 516 μs
  std.net.curl: 505 ms, 811 μs, and 1 hnsec
------------------------------
```
Can you please run your tests with current master?
I'll create new release if there will be no poblems.

Thanks in advance!

**Comment by llJochemll** [comment]
Seems to be working for me!

Tested with master:
    ------------------------------
    Testing https://www.amazon.com
      Requests: 540 ms, 527 ╬╝s, and 2 hnsecs
      std.net.curl: 135 ms, 558 ╬╝s, and 4 hnsecs
    ------------------------------
    ------------------------------
    Testing https://www.google.com
      Requests: 76 ms, 981 ╬╝s, and 4 hnsecs
      std.net.curl: 67 ms, 35 ╬╝s, and 3 hnsecs
    ------------------------------
    ------------------------------
    Testing https://www.bing.com/
      Requests: 108 ms, 557 ╬╝s, and 9 hnsecs
      std.net.curl: 132 ms, 256 ╬╝s, and 9 hnsecs
    ------------------------------

Also tested master in the project I encountered the issue, response times went down to what I expected.

**Comment by ikod** [comment]
Hello, @llJochemll 

Thanks for good news!
I'll make new release.
