### ISSUE TITLE
Timeout exception on content-less 304 response

### ISSUE THREAD

**Issue by forbjok** [ikod/dlang-requests#86]
When specifying an If-Modified-Since header and receiving a 304 status response (which, as expected, has no content), .get() will hang for some time, and eventually throw a timeout exception. The expected behavior (which is what happens when using std.net.curl) would be to return immediately, without throwing an exception, with the 304 status code.

I tested this with httpbin as well, and found that I could not reproduce it there, most likely because httpbin returns a "Content-Length: 0" header, and my test URL (a 4chan thread) does not.

This is likely also an issue in other situations where a content-less response is returned, with no Content-Length header.

Here's a reproduction branch: https://github.com/forbjok/dlang-requests-repro/tree/304-timeout-bug

**Comment by ikod** [comment]
Should be fixed in last commit

**Comment by ikod** [comment]
Hello, @forbjok 
please confirm that it fixed your problem, I'll make some other checks meanwhile.

**Comment by forbjok** [comment]
I can confirm that the problem is fixed in master. Thanks for the quick fix.

**Comment by ikod** [comment]
Thanks for report!
I'll close this issue.

вс, 2 дек. 2018 г., 0:58 forbjok notifications@github.com:

**Comment by ikod** [comment]
Hello, @forbjok 

should be fixed in 1.0.3 release.

Thanks for report!
