### ISSUE TITLE
API doc site is broken

### ISSUE THREAD

**Issue by carun** [ikod/dlang-requests#88]
DDOX API documents hosted at https://ikod.github.io/dlang-requests/ is broken. The root page works, not the sub pages.

**Comment by carun** [comment]
@ikod It would also be nice if Copyright, Author, etc can be populated. If you could point me, I can send a PR as well.

**Comment by ikod** [comment]
Hello, @carun 

Thanks for report.

It was broken after adding dependency. I commited fixed pages on github, but looks like it need some time until it will be visible from github.io.

I'm watching over it.

**Comment by carun** [comment]
Works perfect.

> In dub.json (should be already there)? Or in docs (don't know how I can do it)?

I'm not sure as well. I will raise a PR once I figure it out.
