### ISSUE TITLE
Request._headers read-only access?

### ISSUE THREAD

**Issue by denizzzka** [ikod/dlang-requests#89]
Hi! 

It is possible to provide access to headers? I need to read `Host` header from it

**Comment by denizzzka** [comment]
Yes

**Comment by ikod** [comment]
Yes, this shouldn't be difficult. Hopefully tomorrow will do.

**Comment by denizzzka** [comment]
Thanks!

**Comment by ikod** [comment]
Hello @denizzzka!

Started to work on it, but seems it is already here:
```
> cat h.d
import requests;
import std.stdio;

void main()
{
    Request rq;
    rq.addHeaders(["a":"b"]);
    writeln(rq.headers);
}
> ./h
["a":"b"]
```
Or you need something different?

**Comment by denizzzka** [comment]
It is works for "Host" too?

**Comment by denizzzka** [comment]
> If user add Host header, then yes

I want to read host name generated from URL

**Comment by ikod** [comment]
There are several solutions depending from what you have.
```
import requests;
import std.experimental.logger;
import std.stdio;

void main()
{
    globalLogLevel = LogLevel.info;
    Request rq;
    writeln(URI("http://google.com").host);
    rq.get("https://google.com");
    writeln(rq.uri.host);
}
```
both prints host - first from uri if you know it, second - from the request (after execution)
Can you, please, explain your problem in more details?

**Comment by denizzzka** [comment]
Oh, thanks!

> Can you, please, explain your problem in more details?

Just need to fill out some custom headers using host string
