### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by ZHANITEST** [ikod/dlang-requests#91]
Hello 😄 

I got some error about `sslv3 hanshake`:
```
dub run
Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86.
cachetools 0.0.7: target for configuration "library" is up to date.
requests 1.0.4: target for configuration "std" is up to date.
xx ~master: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running .\xx.exe

object.Exception@..\..\AppData\Local\dub\packages\requests-1.0.4\requests\source\requests\streams.d(797): ssl connect failed: sslv3 alert handshake failure
```

i used pem file from here: https://curl.haxx.se/ca/cacert.pem
and this is my code:
```d
auto rq = Request();
rq.sslSetCaCert("./cacert.pem"); // https://curl.haxx.se/ca/cacert.pem
	
auto x = rq.get("https://dummy.site");
OutBuffer buf = new OutBuffer();
buf.write(x.responseBody.data);
writeln(buf.toString());
```

In my guess like a stupid, this pem file is 'ssl v3' and host(dummy.site) didnt accept v3 because a security. isn't it?

**Comment by ikod** [comment]
Ok, problem not in certificate file, it rather in some incompatibility
between openssl library and site ssl properties. For more detailed answer I
need info on your openssl library version and name of the site.

вс, 23 дек. 2018 г., 9:22 Jone Kimbell notifications@github.com:

**Comment by ZHANITEST** [comment]
Thank you for reply me. 😃 

But, i use the Windows10 x64 and i just install a libssl from here: https://slproweb.com/products/Win32OpenSSL.html

So, i can find libssl.dll from my local storage: `C:\Windows\System32\libssl32.dll`, the version is `1.0.2.16(1.0.2p)`. Hmm... i need to find for new libssl binary for Windows. Or not, need to build that...

Thank you. Pls close this issue if you want.
