### ISSUE TITLE
Remove console error messages for libssl and libcrypto

### ISSUE THREAD

**Issue by michael-fadely** [ikod/dlang-requests#94]
On [this line](https://github.com/ikod/dlang-requests/blob/32527d9900869c63049ef0b834ee2872833bf01f/source/requests/ssl_adapter.d#L95), an error is printed to the console when libssl fails to load. I have no need for libssl and deliberately do not include it, so I would prefer that the library did not print to the console.

As an alternative, perhaps either a build target could be provided that explicitly excludes libssl (or includes; whichever), or a method could be implemented to confirm manually that libssl is loaded.

**Comment by ikod** [comment]
hello @michael-fadely 

Thanks for report, will look how to make it better.

regards

**Comment by ikod** [comment]
Hello @michael-fadely 

should be fixed it master branch. Can you,please, check it?

**Comment by michael-fadely** [comment]
Sorry for the delay. This is a fine solution. Thank you!
