### ISSUE TITLE
Post request not returning cookies

### ISSUE THREAD

**Issue by cyian-1756** [ikod/dlang-requests#95]
I'm using request 1.0.5

I'm trying to log into a site using 

```
void login(string username, string password) {
		Request rq = Request();
		rq.verbosity = 1;
		MultipartForm form;
		form.add(formData("username", username));
		form.add(formData("password", password));
		form.add(formData("remember", "0"));
		rq.addHeaders(["X-Requested-With": "XMLHttpRequest"]);
		rq.addHeaders(["User-Agent": userAgent]);
		Response rs = rq.post("https://NSFWSITE.com/auth/login", form);
		if (rs.code != 200) {
			writefln("Error: Got status code %d", rs.code);
		}
		if (parseJSON(to!string(rs.responseBody))["status"].str != "success") {
			writeln("Unable to login to account!");
			writeln(rs.responseBody);
		}
		auto f = rq.cookie();
		writeln(f.refCountedPayload());
	}
```

However f.refCountedPayload() is always empty. Looking at the debug output I can see that the login worked (a valid cookie was returned) but for whatever reason it is not returned when .cookie() is called

**Comment by ikod** [comment]
Hello @cyian-1756

Thanks for report, will check this problem today.


сб, 2 мар. 2019 г., 23:33 cyian-1756 notifications@github.com:

**Comment by ikod** [comment]
Hello again @cyian-1756 

I can't reproduce problem (although there is some roughness with API which I have to fix). This code works as expected:
```
import std.stdio;
import requests;

void main()
{
    Request rq;
    rq.verbosity = 1;
    Response rs = rq.get("http://httpbin.org/cookies/set?q=qtest");
    auto cookie = rq.cookie._array[0];
    writefln("cookie[\"%s\"] = \"%s\"", cookie.attr, cookie.value);
}
```
and prints:
```
Running ./d 
> GET /cookies/set?q=qtest HTTP/1.1
> User-Agent: dlang-requests
> Accept-Encoding: gzip,deflate
> Connection: Keep-Alive
> Host: httpbin.org
> 
< HTTP/1.1 302 FOUND
< access-control-allow-credentials: true
< access-control-allow-origin: *
< content-type: text/html; charset=utf-8
< date: Sun, 03 Mar 2019 09:55:18 GMT
< location: /cookies
< server: nginx
< set-cookie: q=qtest; Path=/
< content-length: 223
< connection: keep-alive
>> Connect time: 272 ms and 7 μs
>> Request send time: 194 μs
>> Response recv time: 141 ms and 742 μs
> GET /cookies?q=qtest HTTP/1.1
> Cookie: q=qtest
> User-Agent: dlang-requests
> Accept-Encoding: gzip,deflate
> Connection: Keep-Alive
> Host: httpbin.org
> 
< HTTP/1.1 200 OK
< access-control-allow-credentials: true
< access-control-allow-origin: *
< content-encoding: gzip
< content-type: application/json
< date: Sun, 03 Mar 2019 09:55:18 GMT
< server: nginx
< content-length: 55
< connection: keep-alive
>> Connect time: 5 μs
>> Request send time: 95 μs
>> Response recv time: 173 ms and 82 μs
cookie["q"] = "qtest"
```

So to find out what goes wrong in your case I need more info, at least complete output of debug info.
Please wipe out any sensitive info from output before posting here (or you can send it to me directly to igor.khasilev at gmail.com)

Thanks

**Comment by cyian-1756** [comment]
> This code works as expected:

I've only run into this issue when trying to get cookies from POSTs.

> So to find out what goes wrong in your case I need more info, at least complete output of debug info

Here is the output 

```
> POST /auth/login HTTP/1.1
> User-Agent: ChyoaApiForDlang:1
> X-Requested-With: XMLHttpRequest
> Accept-Encoding: gzip,deflate
> Content-Length: 369
> Host: chyoa.com
> Connection: Keep-Alive
> Content-Type: multipart/form-data; boundary=ec377432-b8d4-4cdb-a87f-c655db3c7a31
> 
< HTTP/1.1 200 OK
< date: Sun, 03 Mar 2019 15:36:56 GMT
< content-type: application/json
< transfer-encoding: chunked
< connection: keep-alive
< set-cookie: __cfduid=d9bfbd21bf34c5f97f0c2cf4f769e8b2c1551627416; expires=Mon, 02-Mar-20 15:36:56 GMT; path=/; domain=.chyoa.com; HttpOnly
< vary: Accept-Encoding
< cache-control: no-cache
< set-cookie: laravel_session=REDACTED; expires=Sun, 03-Mar-2019 17:36:56 GMT; Max-Age=7200; path=/; httponly
< set-cookie: remember_82e5d2c56bdd0811318f0cf078b78bfc=REDACTED; expires=Fri, 01-Mar-2024 15:36:56 GMT; Max-Age=157680000; path=/; httponly
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< content-encoding: gzip
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 4b1cb0591c19caaa-YYZ
>> Connect time: 277 ms, 554 μs, and 5 hnsecs
>> Request send time: 274 μs and 3 hnsecs
>> Response recv time: 411 ms, 977 μs, and 9 hnsecs
Cookies([])
```

As you can see the login cookie was returned (remember_82e5d2c56bdd0811318f0cf078b78bfc) but it does not appear in the request cookies

**Comment by ikod** [comment]
hello, @cyian-1756 

as I can see nothing in the cookie handling code depends on method (GET or POST).
There can be something wrong with my cookie handling. Can you give me test login/password to the site, so that I can quickly debug it. There is no big problem if not - I'll try to simulate given replies.

Thanks

**Comment by cyian-1756** [comment]
> Can you give me test login/password to the site, so that I can quickly debug it.

I made a test account

The site is chyoa.com (NSFW)

username: test_account2019

password (base64'd): M3A3cHg1aDV1Nw==

**Comment by ikod** [comment]
Thanks @cyian-1756 

I'm able to reproduce problem, hope will fix soon.

**Comment by ikod** [comment]
Hello @cyian-1756 

Can you please check and report if problem solved with last commit?

Also, probably it is better not to use internal cookie representation (was my bug to make it public), I added `alias this` so that you can simply write code like:

```
    auto f = rq.cookie();

    f.each!writeln;
```

Thanks for your report

**Comment by cyian-1756** [comment]
> Can you please check and report if problem solved with last commit?

Mind walking me thru how to do that? Is there some way to pull from github using dub?

**Comment by cyian-1756** [comment]
Never mind I discovered I could use ~master as the version in dub.json

I can comfirm this is working, thanks for the fix!
